# Generated by Django 5.2.5 on 2025-11-02 16:45

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        db_index=True,
                        help_text="External ID (e.g., 'prop-001')",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "tenure",
                    models.CharField(
                        choices=[
                            ("short_term", "Short Term (Nightly)"),
                            ("long_term", "Long Term (Monthly)"),
                        ],
                        db_index=True,
                        help_text="Rental mode: short_term (nightly) or long_term (monthly)",
                        max_length=16,
                    ),
                ),
                (
                    "price_amount",
                    models.IntegerField(
                        db_index=True,
                        help_text="Price in smallest currency unit (e.g., £120 = 120)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price_unit",
                    models.CharField(
                        choices=[
                            ("per_night", "Per Night"),
                            ("per_month", "Per Month"),
                        ],
                        db_index=True,
                        help_text="per_night or per_month",
                        max_length=16,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GBP", help_text="ISO 4217 currency code", max_length=3
                    ),
                ),
                (
                    "bedrooms",
                    models.IntegerField(
                        db_index=True,
                        default=1,
                        help_text="Number of bedrooms",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "bathrooms",
                    models.IntegerField(
                        default=1,
                        help_text="Number of bathrooms",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_guests",
                    models.IntegerField(
                        default=2,
                        help_text="Maximum occupancy (relevant for short-term)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("villa", "Villa"),
                            ("studio", "Studio"),
                            ("house", "House"),
                            ("penthouse", "Penthouse"),
                        ],
                        db_index=True,
                        default="apartment",
                        help_text="Type of property",
                        max_length=32,
                    ),
                ),
                (
                    "square_meters",
                    models.IntegerField(
                        blank=True,
                        help_text="Property size in square meters",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "amenities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        blank=True,
                        default=list,
                        help_text="List of amenities: wifi, pool, parking, air_conditioning, etc.",
                        size=None,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True,
                        help_text="City (e.g., 'Kyrenia', 'Famagusta')",
                        max_length=64,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Neighborhood or area (optional)",
                        max_length=64,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Full address (optional, for display only)",
                        max_length=200,
                    ),
                ),
                (
                    "min_stay_nights",
                    models.IntegerField(
                        default=1,
                        help_text="Minimum stay for short-term rentals (nights)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "min_lease_months",
                    models.IntegerField(
                        default=1,
                        help_text="Minimum lease duration for long-term rentals (months)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "available_from",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Earliest move-in date for long-term rentals (ISO 8601)",
                        null=True,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, default="", help_text="Primary image URL"
                    ),
                ),
                (
                    "additional_images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(),
                        blank=True,
                        default=list,
                        help_text="Additional image URLs",
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether listing is currently active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Real Estate Listing",
                "verbose_name_plural": "Real Estate Listings",
                "ordering": ["price_amount", "title"],
                "indexes": [
                    models.Index(
                        fields=["tenure", "city", "bedrooms", "price_amount"],
                        name="re_main_search_idx",
                    ),
                    models.Index(
                        fields=["tenure", "available_from", "city"],
                        name="re_movein_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="Date (ISO 8601: YYYY-MM-DD)"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the property is available on this date",
                    ),
                ),
                (
                    "price_override",
                    models.IntegerField(
                        blank=True,
                        help_text="Optional price override for this specific date (e.g., peak season)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        help_text="Short-term listing this availability belongs to",
                        limit_choices_to={"tenure": "short_term"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_calendar",
                        to="real_estate.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Availability",
                "verbose_name_plural": "Availability Calendar",
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["listing", "date", "is_available"],
                        name="re_avail_lookup_idx",
                    )
                ],
                "unique_together": {("listing", "date")},
            },
        ),
    ]
