# Generated by Django 5.0.4 on 2025-11-12 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "city",
                    models.CharField(
                        db_index=True,
                        help_text="City name (e.g., 'Girne', 'Kyrenia', 'Lefkoşa')",
                        max_length=80,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="District or neighborhood (e.g., 'Karakum', 'Alsancak')",
                        max_length=80,
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude (WGS84)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude (WGS84)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("bedrooms", models.IntegerField(db_index=True)),
                (
                    "bathrooms",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        help_text="Number of bathrooms (supports .5 for half-bath)",
                        max_digits=3,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        default="apartment",
                        help_text="apartment, villa, studio, house, penthouse",
                        max_length=40,
                    ),
                ),
                (
                    "rent_type",
                    models.CharField(
                        choices=[
                            ("short_term", "short_term"),
                            ("long_term", "long_term"),
                            ("both", "both"),
                        ],
                        db_index=True,
                        default="both",
                        help_text="short_term (nightly), long_term (monthly), or both",
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GBP",
                        help_text="ISO 4217: GBP, EUR, USD, TRY",
                        max_length=3,
                    ),
                ),
                (
                    "monthly_price",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Monthly rent (applicable if rent_type=long_term or both)",
                        null=True,
                    ),
                ),
                (
                    "available_from",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Earliest move-in date for long-term (ISO 8601)",
                        null=True,
                    ),
                ),
                (
                    "min_term_months",
                    models.IntegerField(
                        blank=True,
                        help_text="Minimum lease duration in months",
                        null=True,
                    ),
                ),
                (
                    "deposit",
                    models.IntegerField(
                        blank=True,
                        help_text="Security deposit amount (typically 1-2 months rent)",
                        null=True,
                    ),
                ),
                (
                    "nightly_price",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Nightly rate (applicable if rent_type=short_term or both)",
                        null=True,
                    ),
                ),
                (
                    "min_nights",
                    models.IntegerField(
                        blank=True, help_text="Minimum stay in nights", null=True
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of amenity codes: ["ac", "wifi", "sea_view", "pool", "parking"]',
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of image URLs: ["https://.../1.jpg", "https://.../2.jpg"]',
                    ),
                ),
                (
                    "agency_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of listing agency or landlord",
                        max_length=120,
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        blank=True, help_text="User rating (0.0-5.0)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings",
                "ordering": ["city", "bedrooms", "monthly_price"],
                "indexes": [
                    models.Index(
                        fields=["rent_type", "city", "bedrooms", "monthly_price"],
                        name="re_lt_search_idx",
                    ),
                    models.Index(
                        fields=["rent_type", "city", "bedrooms", "nightly_price"],
                        name="re_st_search_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShortTermBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_index=True,
                        help_text="Start date of blocked range (inclusive)",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        db_index=True, help_text="End date of blocked range (inclusive)"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        help_text="Short-term listing this block applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="st_blocks",
                        to="real_estate.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Short-Term Block",
                "verbose_name_plural": "Short-Term Blocks",
                "ordering": ["start_date"],
                "indexes": [
                    models.Index(
                        fields=["listing", "start_date", "end_date"],
                        name="re_stblock_lookup_idx",
                    )
                ],
            },
        ),
    ]
