# Generated by Django 5.2.5 on 2025-11-14 18:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., 'INSIDE', 'OUTSIDE', 'VIEW', 'AMENITY'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Feature Category",
                "verbose_name_plural": "Feature Categories",
            },
        ),
        migrations.CreateModel(
            name="ListingType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., 'DAILY_RENTAL', 'SALE'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Listing Type",
                "verbose_name_plural": "Listing Types",
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., 'APARTMENT', 'VILLA_TRIPLEX'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="Human readable name", max_length=100),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RESIDENTIAL", "Residential"),
                            ("COMMERCIAL", "Commercial"),
                            ("LAND", "Land"),
                        ],
                        default="RESIDENTIAL",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Type",
                "verbose_name_plural": "Property Types",
            },
        ),
        migrations.CreateModel(
            name="TaxType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., 'ELECTRICITY_TAX', 'PROPERTY_TAX'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tax Type",
                "verbose_name_plural": "Tax Types",
            },
        ),
        migrations.CreateModel(
            name="TitleDeedType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., 'TURKISH', 'EXCHANGE'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Title Deed Type",
                "verbose_name_plural": "Title Deed Types",
            },
        ),
        migrations.CreateModel(
            name="UtilityType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., 'ELECTRICITY', 'WATER', 'INTERNET'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Utility Type",
                "verbose_name_plural": "Utility Types",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "indexes": [
                    models.Index(fields=["phone"], name="real_estate_phone_bbc908_idx"),
                    models.Index(fields=["email"], name="real_estate_email_58a6c5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to="real_estate.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., 'BALCONY', 'WIFI', 'PRIVATE_POOL'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                (
                    "is_required_for_daily_rental",
                    models.BooleanField(
                        default=False, help_text="Required for short-term rentals"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="features",
                        to="real_estate.featurecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="portal, walk-in, instagram, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CONTACTED", "Contacted"),
                            ("QUALIFIED", "Qualified"),
                            ("LOST", "Lost"),
                            ("CONVERTED", "Converted"),
                        ],
                        default="NEW",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead",
                        to="real_estate.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reference_code",
                    models.CharField(
                        help_text="e.g., 'EI-L-000123'", max_length=50, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="EUR", max_length=10)),
                (
                    "price_period",
                    models.CharField(
                        choices=[
                            ("PER_DAY", "Per day"),
                            ("PER_MONTH", "Per month"),
                            ("TOTAL", "Total"),
                            ("STARTING_FROM", "Starting from"),
                        ],
                        default="TOTAL",
                        max_length=20,
                    ),
                ),
                ("available_from", models.DateField(blank=True, null=True)),
                ("available_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("UNDER_OFFER", "Under Offer"),
                            ("SOLD", "Sold"),
                            ("RENTED", "Rented"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Main landlord/seller",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owner_listings",
                        to="real_estate.contact",
                    ),
                ),
                (
                    "listing_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="real_estate.listingtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings",
            },
        ),
        migrations.CreateModel(
            name="ListingEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("VIEW", "View"),
                            ("ENQUIRY", "Enquiry"),
                            ("BOOKING_REQUEST", "Booking Request"),
                            ("BOOKING_CONFIRMED", "Booking Confirmed"),
                            ("WHATSAPP_CLICK", "WhatsApp Click"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="web, mobile, portal, etc.", max_length=50
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="real_estate.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing Event",
                "verbose_name_plural": "Listing Events",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("country", models.CharField(default="Cyprus", max_length=64)),
                (
                    "region",
                    models.CharField(help_text="e.g., 'North Cyprus'", max_length=64),
                ),
                ("city", models.CharField(help_text="e.g., 'Kyrenia'", max_length=64)),
                (
                    "area",
                    models.CharField(help_text="e.g., 'Esentepe'", max_length=128),
                ),
                ("address_line", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "indexes": [
                    models.Index(
                        fields=["city", "area"], name="real_estate_city_c34691_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("total_units", models.IntegerField(blank=True, null=True)),
                ("completion_date_estimate", models.DateField(blank=True, null=True)),
                (
                    "min_unit_area_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "max_unit_area_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=10)),
                (
                    "payment_plan_json",
                    models.JSONField(
                        blank=True, default=dict, help_text="Flexible payment plans"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "developer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="developed_projects",
                        to="real_estate.contact",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="real_estate.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="real_estate.project",
            ),
        ),
        migrations.CreateModel(
            name="ProjectListingDetails",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "min_unit_area_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "max_unit_area_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("payment_plan_json", models.JSONField(blank=True, default=dict)),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_details",
                        to="real_estate.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Listing Details",
                "verbose_name_plural": "Project Listing Details",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reference_code",
                    models.CharField(
                        help_text="e.g., 'EI-RE-000123'", max_length=50, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("building_name", models.CharField(blank=True, max_length=255)),
                ("flat_number", models.CharField(blank=True, max_length=50)),
                ("floor_number", models.IntegerField(blank=True, null=True)),
                (
                    "total_area_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "net_area_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("bedrooms", models.IntegerField(default=0)),
                ("living_rooms", models.IntegerField(default=1)),
                ("bathrooms", models.IntegerField(default=1)),
                (
                    "room_configuration_label",
                    models.CharField(
                        blank=True, help_text="e.g., '2+1'", max_length=20
                    ),
                ),
                (
                    "furnished_status",
                    models.CharField(
                        choices=[
                            ("UNFURNISHED", "Unfurnished"),
                            ("PARTLY_FURNISHED", "Partly Furnished"),
                            ("FULLY_FURNISHED", "Fully Furnished"),
                        ],
                        default="UNFURNISHED",
                        max_length=20,
                    ),
                ),
                ("floor_of_building", models.IntegerField(blank=True, null=True)),
                ("total_floors", models.IntegerField(blank=True, null=True)),
                (
                    "year_built",
                    models.IntegerField(
                        blank=True,
                        help_text="Year built (for property age calculation)",
                        null=True,
                    ),
                ),
                ("is_gated_community", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="real_estate.location",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="units",
                        to="real_estate.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="real_estate.property",
            ),
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "deal_type",
                    models.CharField(
                        choices=[
                            ("RENTAL", "Rental"),
                            ("SALE", "Sale"),
                            ("PROJECT_SALE", "Project Sale"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("NEGOTIATION", "Negotiation"),
                            ("RESERVATION", "Reservation"),
                            ("CONTRACT_SIGNED", "Contract Signed"),
                            ("CLOSED_WON", "Closed Won"),
                            ("CLOSED_LOST", "Closed Lost"),
                        ],
                        default="NEW",
                        max_length=30,
                    ),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                ("actual_close_date", models.DateField(blank=True, null=True)),
                (
                    "agreed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=10)),
                (
                    "commission_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deals",
                        to="real_estate.client",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="real_estate.listing",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="real_estate.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal",
                "verbose_name_plural": "Deals",
            },
        ),
        migrations.CreateModel(
            name="PropertyFeature",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="real_estate.feature",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Feature",
                "verbose_name_plural": "Property Features",
            },
        ),
        migrations.AddField(
            model_name="property",
            name="features",
            field=models.ManyToManyField(
                related_name="properties",
                through="real_estate.PropertyFeature",
                to="real_estate.feature",
            ),
        ),
        migrations.CreateModel(
            name="PropertyOwner",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "ownership_percentage",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_properties",
                        to="real_estate.contact",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="real_estate.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Owner",
                "verbose_name_plural": "Property Owners",
            },
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="real_estate.propertytype",
            ),
        ),
        migrations.CreateModel(
            name="RentalDetails",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "rental_kind",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily / Short Term"),
                            ("LONG_TERM", "Long Term"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_days",
                    models.IntegerField(
                        blank=True, help_text="For daily rentals", null=True
                    ),
                ),
                (
                    "min_months",
                    models.IntegerField(
                        blank=True, help_text="For long term", null=True
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("deposit_currency", models.CharField(default="EUR", max_length=10)),
                (
                    "utilities_included",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="e.g., {'ELECTRICITY': false, 'WATER': true}",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_details",
                        to="real_estate.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rental Details",
                "verbose_name_plural": "Rental Details",
            },
        ),
        migrations.CreateModel(
            name="SaleDetails",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "is_swap_possible",
                    models.BooleanField(default=False, help_text="Swap type deals"),
                ),
                ("negotiable", models.BooleanField(default=True)),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_details",
                        to="real_estate.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale Details",
                "verbose_name_plural": "Sale Details",
            },
        ),
        migrations.CreateModel(
            name="PropertyTax",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=10)),
                (
                    "billing_period",
                    models.CharField(
                        blank=True, help_text="monthly, yearly, etc.", max_length=20
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="real_estate.property",
                    ),
                ),
                (
                    "tax_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="real_estate.taxtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Tax",
                "verbose_name_plural": "Property Taxes",
            },
        ),
        migrations.CreateModel(
            name="Tenancy",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tenancy_kind",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily / Short Term"),
                            ("LONG_TERM", "Long Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("rent_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("rent_currency", models.CharField(default="EUR", max_length=10)),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("ENDED", "Ended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenancies",
                        to="real_estate.listing",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenancies",
                        to="real_estate.property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenancies",
                        to="real_estate.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenancy",
                "verbose_name_plural": "Tenancies",
            },
        ),
        migrations.AddField(
            model_name="property",
            name="title_deed_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="real_estate.titledeedtype",
            ),
        ),
        migrations.CreateModel(
            name="PropertyUtilityAccount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("provider_name", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=100)),
                ("meter_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_accounts",
                        to="real_estate.property",
                    ),
                ),
                (
                    "utility_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="real_estate.utilitytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Utility Account",
                "verbose_name_plural": "Property Utility Accounts",
            },
        ),
        migrations.CreateModel(
            name="ContactRole",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LEAD", "Lead"),
                            ("CLIENT", "Client"),
                            ("OWNER", "Owner"),
                            ("TENANT", "Tenant"),
                            ("AGENT", "Agent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("active_from", models.DateField(default=django.utils.timezone.now)),
                ("active_to", models.DateField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="real_estate.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Role",
                "verbose_name_plural": "Contact Roles",
                "unique_together": {("contact", "role")},
            },
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(
                fields=["category"], name="real_estate_categor_760f16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listingevent",
            index=models.Index(
                fields=["listing", "event_type"], name="real_estate_listing_f02562_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listingevent",
            index=models.Index(
                fields=["occurred_at"], name="real_estate_occurre_23e88b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["listing_type", "status"], name="real_estate_listing_e9dec7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["property"], name="real_estate_propert_9aa4e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["project"], name="real_estate_project_d18ad1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["reference_code"], name="real_estate_referen_f729ae_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertyfeature",
            unique_together={("property", "feature")},
        ),
        migrations.AlterUniqueTogether(
            name="propertyowner",
            unique_together={("property", "contact")},
        ),
        migrations.AlterUniqueTogether(
            name="propertytax",
            unique_together={("property", "tax_type")},
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["location", "property_type"],
                name="real_estate_locatio_403f47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["reference_code"], name="real_estate_referen_7e6901_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertyutilityaccount",
            unique_together={("property", "utility_type")},
        ),
    ]
