# Generated by Django 5.0.4 on 2025-11-08 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortTermBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_index=True,
                        help_text="Start date of blocked range (inclusive)",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        db_index=True, help_text="End date of blocked range (inclusive)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Short-Term Block",
                "verbose_name_plural": "Short-Term Blocks",
                "ordering": ["start_date"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="availability",
            name="listing",
        ),
        migrations.AlterModelOptions(
            name="listing",
            options={
                "ordering": ["city", "bedrooms", "monthly_price"],
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings",
            },
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="re_main_search_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="re_movein_idx",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="additional_images",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="address",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="area",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="max_guests",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="min_lease_months",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="min_stay_nights",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="price_amount",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="price_unit",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="square_meters",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="tenure",
        ),
        migrations.AddField(
            model_name="listing",
            name="agency_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of listing agency or landlord",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="deposit",
            field=models.IntegerField(
                blank=True,
                help_text="Security deposit amount (typically 1-2 months rent)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="district",
            field=models.CharField(
                blank=True,
                default="",
                help_text="District or neighborhood (e.g., 'Karakum', 'Alsancak')",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="images",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of image URLs: ["https://.../1.jpg", "https://.../2.jpg"]',
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude (WGS84)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude (WGS84)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="min_nights",
            field=models.IntegerField(
                blank=True, help_text="Minimum stay in nights", null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="min_term_months",
            field=models.IntegerField(
                blank=True, help_text="Minimum lease duration in months", null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="monthly_price",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Monthly rent (applicable if rent_type=long_term or both)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="nightly_price",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Nightly rate (applicable if rent_type=short_term or both)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="rating",
            field=models.FloatField(
                blank=True, help_text="User rating (0.0-5.0)", null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="rent_type",
            field=models.CharField(
                choices=[
                    ("short_term", "short_term"),
                    ("long_term", "long_term"),
                    ("both", "both"),
                ],
                db_index=True,
                default="both",
                help_text="short_term (nightly), long_term (monthly), or both",
                max_length=10,
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE real_estate_listing "
                'ALTER COLUMN "amenities" TYPE jsonb USING to_jsonb("amenities");'
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="listing",
            name="amenities",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of amenity codes: ["ac", "wifi", "sea_view", "pool", "parking"]',
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="available_from",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Earliest move-in date for long-term (ISO 8601)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="bathrooms",
            field=models.DecimalField(
                decimal_places=1,
                default=1.0,
                help_text="Number of bathrooms (supports .5 for half-bath)",
                max_digits=3,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="bedrooms",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="city",
            field=models.CharField(
                db_index=True,
                help_text="City name (e.g., 'Girne', 'Kyrenia', 'Lefkoşa')",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="currency",
            field=models.CharField(
                default="GBP", help_text="ISO 4217: GBP, EUR, USD, TRY", max_length=3
            ),
        ),
        migrations.RunSQL(
            sql=(
                # Drop identity first to satisfy Postgres requirements; then drop any default.
                'ALTER TABLE real_estate_listing ALTER COLUMN "id" DROP IDENTITY IF EXISTS; '
                'ALTER TABLE real_estate_listing ALTER COLUMN "id" DROP DEFAULT; '
                # Convert existing bigint PKs to deterministic UUIDs (md5 of id cast via uuid_in).
                'ALTER TABLE real_estate_listing '
                'ALTER COLUMN "id" TYPE uuid USING uuid_in(md5("id"::text)::cstring);'
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="listing",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="property_type",
            field=models.CharField(
                default="apartment",
                help_text="apartment, villa, studio, house, penthouse",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(max_length=160),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["rent_type", "city", "bedrooms", "monthly_price"],
                name="re_lt_search_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["rent_type", "city", "bedrooms", "nightly_price"],
                name="re_st_search_idx",
            ),
        ),
        migrations.AddField(
            model_name="shorttermblock",
            name="listing",
            field=models.ForeignKey(
                help_text="Short-term listing this block applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="st_blocks",
                to="real_estate.listing",
            ),
        ),
        migrations.DeleteModel(
            name="Availability",
        ),
        migrations.AddIndex(
            model_name="shorttermblock",
            index=models.Index(
                fields=["listing", "start_date", "end_date"],
                name="re_stblock_lookup_idx",
            ),
        ),
    ]
