# Generated by Django 5.0.4 on 2025-11-15 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0002_create_search_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaDemographics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("socio_economic_grade", models.CharField(blank=True, max_length=20)),
                ("data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Area Demographics",
                "verbose_name_plural": "Area Demographics",
            },
        ),
        migrations.CreateModel(
            name="AreaMarketStats",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("RENT_PRICE_PER_SQM", "Rent price per m²"),
                            ("SALE_PRICE_PER_SQM", "Sale price per m²"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Area Market Stats",
                "verbose_name_plural": "Area Market Stats",
            },
        ),
        migrations.CreateModel(
            name="ProjectUnitType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., '3BED Villa with Private Pool and Garden'",
                        max_length=255,
                    ),
                ),
                ("bedrooms", models.IntegerField(default=0)),
                ("living_rooms", models.IntegerField(default=1)),
                ("bathrooms", models.IntegerField(default=1)),
                (
                    "room_configuration_label",
                    models.CharField(
                        blank=True, help_text="e.g., '3+1'", max_length=20
                    ),
                ),
                ("area_sqm", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="EUR", max_length=10)),
            ],
            options={
                "verbose_name": "Project Unit Type",
                "verbose_name_plural": "Project Unit Types",
            },
        ),
        migrations.AlterModelOptions(
            name="feature",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
            },
        ),
        migrations.AlterModelOptions(
            name="featurecategory",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "Feature Category",
                "verbose_name_plural": "Feature Categories",
            },
        ),
        migrations.AddField(
            model_name="feature",
            name="applicable_property_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="If empty, feature is applicable to all property types.",
                related_name="applicable_features",
                to="real_estate.propertytype",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="group",
            field=models.CharField(
                choices=[
                    ("INTERNAL", "Internal"),
                    ("EXTERNAL", "External"),
                    ("LOCATION", "Location"),
                    ("SAFETY", "Safety"),
                    ("BUILDING", "Building"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="is_filterable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="feature",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="featurecategory",
            name="sort_order",
            field=models.IntegerField(
                default=0, help_text="Display ordering for filter panels"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="analytics_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Derived stats such as average price per m², mix of unit types, etc.",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="feature",
            name="code",
            field=models.CharField(
                help_text="e.g., 'ac', 'pool_private', 'sea_view'",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="featurecategory",
            name="code",
            field=models.CharField(
                help_text="e.g., 'INTERNAL', 'EXTERNAL', 'LOCATION'",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(
                fields=["group", "sort_order"], name="real_estate_group_ba9568_idx"
            ),
        ),
        migrations.AddField(
            model_name="areademographics",
            name="location",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demographics",
                to="real_estate.location",
            ),
        ),
        migrations.AddField(
            model_name="areamarketstats",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market_stats",
                to="real_estate.location",
            ),
        ),
        migrations.AddField(
            model_name="areamarketstats",
            name="property_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="market_stats",
                to="real_estate.propertytype",
            ),
        ),
        migrations.AddField(
            model_name="projectunittype",
            name="features",
            field=models.ManyToManyField(
                blank=True, related_name="project_unit_types", to="real_estate.feature"
            ),
        ),
        migrations.AddField(
            model_name="projectunittype",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_types",
                to="real_estate.project",
            ),
        ),
        migrations.AddField(
            model_name="projectunittype",
            name="property_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_unit_types",
                to="real_estate.propertytype",
            ),
        ),
        migrations.AddIndex(
            model_name="areamarketstats",
            index=models.Index(
                fields=["location", "property_type", "metric"],
                name="real_estate_locatio_31758c_idx",
            ),
        ),
    ]
