# Generated by Claude Code on 2025-11-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_areademographics_areamarketstats_projectunittype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='real_estate/properties/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.listing')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['display_order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'display_order'], name='real_estate_propert_b3e8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['listing', 'display_order'], name='real_estate_listing_9a4c2d_idx'),
        ),
    ]
