# Generated by Django 5.0.4 on 2025-11-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0003_update_search_view_images"),
        ("real_estate", "0004_propertyimage"),
    ]

    operations = []
