# Generated by Django 5.0.4 on 2025-11-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0005_merge_20251118_1741"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="propertyimage",
            new_name="real_estate_propert_2931bf_idx",
            old_name="real_estate_propert_b3e8eb_idx",
        ),
        migrations.RenameIndex(
            model_name="propertyimage",
            new_name="real_estate_listing_88cd23_idx",
            old_name="real_estate_listing_9a4c2d_idx",
        ),
        migrations.AddField(
            model_name="tenancy",
            name="booking_reference",
            field=models.CharField(
                blank=True,
                help_text="Unique booking reference code (e.g., BK-20251118-1234)",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="tenancy",
            name="guest_count",
            field=models.IntegerField(default=1, help_text="Number of guests"),
        ),
        migrations.AddField(
            model_name="tenancy",
            name="guest_email",
            field=models.EmailField(
                blank=True, help_text="Guest's email address", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="tenancy",
            name="guest_name",
            field=models.CharField(
                blank=True, help_text="Guest's full name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="tenancy",
            name="guest_phone",
            field=models.CharField(
                blank=True, help_text="Guest's phone number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="tenancy",
            name="payment_method",
            field=models.CharField(
                blank=True,
                help_text="Payment method used (e.g., Credit Card, PayPal)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tenancy",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("REFUNDED", "Refunded"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                help_text="Payment status for this booking",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenancy",
            name="special_requests",
            field=models.TextField(
                blank=True, help_text="Special requests or notes from the guest"
            ),
        ),
        migrations.AddIndex(
            model_name="tenancy",
            index=models.Index(
                fields=["listing", "status"], name="real_estate_listing_52d345_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenancy",
            index=models.Index(
                fields=["booking_reference"], name="real_estate_booking_a1dc09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenancy",
            index=models.Index(
                fields=["start_date", "end_date"], name="real_estate_start_d_b809a9_idx"
            ),
        ),
    ]
