# Generated by Django 5.0.4 on 2025-11-12 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentRegistry",
            fields=[
                (
                    "agent_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("domain", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("coverage", models.JSONField(default=dict)),
                ("version", models.CharField(default="v1", max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="DomainCentroid",
            fields=[
                (
                    "domain",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("vector", models.JSONField(default=list)),
                ("support_n", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CalibrationParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=64)),
                ("method", models.CharField(default="platt", max_length=16)),
                (
                    "params",
                    models.JSONField(
                        default=dict,
                        help_text="Calibration parameters (weights, intercepts, etc.)",
                    ),
                ),
                (
                    "ece",
                    models.FloatField(
                        default=0.0, help_text="Expected Calibration Error"
                    ),
                ),
                (
                    "support_n",
                    models.IntegerField(
                        default=0, help_text="Number of samples used for calibration"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="active",
                        help_text="Version tag (active, shadow, v20240101, etc.)",
                        max_length=32,
                    ),
                ),
                ("evaluated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["evaluated_on"], name="router_serv_evaluat_111110_idx"
                    ),
                    models.Index(
                        fields=["version"], name="router_serv_version_f11575_idx"
                    ),
                ],
                "unique_together": {("domain", "version")},
            },
        ),
        migrations.CreateModel(
            name="IntentExemplar",
            fields=[
                (
                    "exemplar_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("intent_key", models.CharField(max_length=128)),
                ("text", models.TextField()),
                ("vector", models.JSONField(default=list)),
                ("locale", models.CharField(blank=True, max_length=16)),
                ("geo_region", models.CharField(blank=True, max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["intent_key"], name="router_serv_intent__806d03_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RouterEvent",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("thread_id", models.CharField(blank=True, max_length=64)),
                ("utterance", models.TextField()),
                ("context_hint", models.JSONField(default=dict)),
                ("stage1_safe", models.BooleanField(default=True)),
                ("domain_pred", models.CharField(blank=True, max_length=64)),
                ("domain_conf", models.FloatField(default=0.0)),
                ("in_domain_intent", models.CharField(blank=True, max_length=64)),
                ("action", models.CharField(blank=True, max_length=32)),
                ("latency_ms", models.IntegerField(default=0)),
                ("cost_cents", models.FloatField(blank=True, null=True)),
                (
                    "split",
                    models.CharField(
                        choices=[
                            ("train", "Training"),
                            ("val", "Validation"),
                            ("test", "Testing"),
                        ],
                        default="train",
                        max_length=8,
                    ),
                ),
                (
                    "correct_label",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="router_serv_created_411ff0_idx"
                    ),
                    models.Index(
                        fields=["domain_pred"], name="router_serv_domain__7497ec_idx"
                    ),
                    models.Index(fields=["split"], name="router_serv_split_0685ac_idx"),
                    models.Index(fields=["-created_at"], name="router_evt_created_idx"),
                    models.Index(
                        fields=["domain_pred", "-created_at"],
                        name="router_evt_domain_idx",
                    ),
                ],
            },
        ),
    ]
