# Generated by Django 5.0.4 on 2025-10-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("router_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="intentexemplar",
            new_name="router_serv_intent__806d03_idx",
            old_name="intent_exem_intent_Idx",
        ),
        migrations.RenameIndex(
            model_name="routerevent",
            new_name="router_serv_created_411ff0_idx",
            old_name="router_even_created_Idx",
        ),
        migrations.RenameIndex(
            model_name="routerevent",
            new_name="router_serv_domain__7497ec_idx",
            old_name="router_even_domain_Idx",
        ),
    ]
