# Generated by Django 5.2.5 on 2025-10-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_service', '0002_rename_intent_exem_intent_idx_router_serv_intent__806d03_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationParams',
            fields=[
                ('domain', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('method', models.CharField(default='platt', max_length=16)),
                ('params', models.JSONField(default=dict, help_text='Calibration parameters (weights, intercepts, etc.)')),
                ('ece', models.FloatField(default=0.0, help_text='Expected Calibration Error')),
                ('support_n', models.IntegerField(default=0, help_text='Number of samples used for calibration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='router_serv_updated_63c726_idx')],
            },
        ),
    ]
