# Generated by Django 5.2.5 on 2025-10-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('router_service', '0003_calibrationparams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationparams',
            old_name='domain',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='calibrationparams',
            old_name='updated_at',
            new_name='evaluated_on',
        ),
        migrations.RemoveField(
            model_name='calibrationparams',
            name='ece',
        ),
        migrations.RemoveField(
            model_name='calibrationparams',
            name='support_n',
        ),
    ]
