# Generated by Django 5.2.5 on 2025-10-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_service', '0004_auto_20251028_1600'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calibrationparams',
            name='router_serv_updated_63c726_idx',
        ),
        migrations.AddIndex(
            model_name='calibrationparams',
            index=models.Index(fields=['evaluated_on'], name='router_serv_evaluat_111110_idx'),
        ),
    ]
