# Generated by Django 5.2.5 on 2025-10-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_service', '0005_remove_calibrationparams_router_serv_updated_63c726_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerevent',
            name='correct_label',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='routerevent',
            name='split',
            field=models.CharField(choices=[('train', 'Training'), ('val', 'Validation'), ('test', 'Testing')], default='train', max_length=8),
        ),
        migrations.AddIndex(
            model_name='routerevent',
            index=models.Index(fields=['split'], name='router_serv_split_0685ac_idx'),
        ),
    ]
