# Generated by Django 5.2.5 on 2025-10-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('router_service', '0007_alter_calibrationparams_unique_together_and_more'),
    ]

    operations = [
    ]
