# Generated by Django 5.0.4 on 2025-10-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("router_service", "0008_auto_20251028_1836"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="routerevent",
            index=models.Index(fields=["-created_at"], name="router_evt_created_idx"),
        ),
        migrations.AddIndex(
            model_name="routerevent",
            index=models.Index(
                fields=["domain_pred", "-created_at"], name="router_evt_domain_idx"
            ),
        ),
    ]
