# Generated by Django 5.2.5 on 2025-11-12 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preference_type",
                    models.CharField(
                        choices=[
                            ("ui_language", "UI Language"),
                            ("ui_currency", "UI Currency"),
                            ("ui_timezone", "UI Timezone"),
                            ("ui_email_notifications", "Email Notifications"),
                            ("ui_push_notifications", "Push Notifications"),
                            ("ui_marketing_notifications", "Marketing Notifications"),
                            ("extracted_real_estate", "Real Estate Preferences"),
                            ("extracted_services", "Services Preferences"),
                            ("extracted_lifestyle", "Lifestyle Preferences"),
                            ("extracted_general", "General Preferences"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("value", models.JSONField(help_text="Normalized structured value")),
                (
                    "raw_value",
                    models.TextField(
                        blank=True, help_text="Original utterance (PII-redacted)"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0, help_text="Confidence score (0.0-1.0)"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("explicit", "Explicitly Stated"),
                            ("inferred", "Inferred from Context"),
                            ("behavior", "Learned from Behavior"),
                            ("system_default", "System Default"),
                        ],
                        default="explicit",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("use_count", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "ordering": ["-confidence", "-last_used_at"],
            },
        ),
        migrations.DeleteModel(
            name="UserPreferences",
        ),
        migrations.AddIndex(
            model_name="userpreference",
            index=models.Index(
                fields=["user", "preference_type"], name="user_pref_user_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userpreference",
            index=models.Index(
                fields=["user", "-confidence"], name="user_pref_confidence_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userpreference",
            index=models.Index(
                fields=["-confidence", "-last_used_at"],
                name="user_pref_conf_lastused_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userpreference",
            unique_together={("user", "preference_type")},
        ),
    ]
