# Generated by Django 5.2.5 on 2025-11-12 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userpreference_delete_userpreferences_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("real_estate", "Real Estate"),
                            ("events", "Events & Entertainment"),
                            ("activities", "Activities & Tours"),
                            ("appointments", "Appointments & Services"),
                            ("vehicles", "Vehicle Rentals"),
                            ("hospitality", "Hospitality & Accommodation"),
                            ("food_beverage", "Food & Beverage"),
                            ("health_wellness", "Health & Wellness"),
                            ("education", "Education & Training"),
                            ("professional_services", "Professional Services"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary business domain selected during onboarding",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this domain is currently active",
                    ),
                ),
                ("onboarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "setup_completed",
                    models.BooleanField(
                        default=False, help_text="Has completed domain-specific setup"
                    ),
                ),
                ("total_listings", models.IntegerField(default=0)),
                ("total_bookings", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Domain-specific settings and preferences",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_domains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Domain",
                "verbose_name_plural": "Business Domains",
                "ordering": ["-is_primary", "-total_revenue", "domain"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="biz_dom_user_active_idx"
                    ),
                    models.Index(
                        fields=["user", "is_primary"], name="biz_dom_user_primary_idx"
                    ),
                    models.Index(
                        fields=["domain", "is_active"], name="biz_dom_domain_active_idx"
                    ),
                ],
                "unique_together": {("user", "domain")},
            },
        ),
    ]
