# Generated by Django 5.2.5 on 2025-11-17 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_businessdomain"),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='listings.Category',
            ),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='subcategory',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='listings.Subcategory',
            ),
        ),
    ]
