const lineClamp = require('@tailwindcss/line-clamp');
const animate = require('tailwindcss-animate');
const { heroui } = require('@heroui/theme');

module.exports = {
  darkMode: ["class"],
  content: [
    'src/**/*.{ts,tsx,jsx,js}',
    'index.html',
  ],
  theme: {
    container: {
      center: true,
      padding: "3rem",
      screens: {
        "2xl": "1400px",
        "3xl": "1600px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['var(--font-display)', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      borderRadius: {
        xl: '0.75rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        pill: '9999px',
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      boxShadow: {
        xs: '0 1px 2px 0 rgba(15, 23, 42, 0.05)',
        sm: '0 1px 3px 0 rgba(15, 23, 42, 0.1), 0 1px 2px 0 rgba(15, 23, 42, 0.06)',
        md: '0 4px 6px -1px rgba(15, 23, 42, 0.1), 0 2px 4px -1px rgba(15, 23, 42, 0.06)',
        lg: '0 10px 15px -3px rgba(15, 23, 42, 0.1), 0 4px 6px -2px rgba(15, 23, 42, 0.05)',
        xl: '0 20px 25px -5px rgba(15, 23, 42, 0.1), 0 10px 10px -5px rgba(15, 23, 42, 0.04)',
        '2xl': '0 25px 50px -12px rgba(15, 23, 42, 0.25)',
        'inner-soft': 'inset 0 2px 4px 0 rgba(15, 23, 42, 0.06)',
        'glow-brand': '0 0 20px rgba(108, 194, 74, 0.3)',
        'glow-gold': '0 0 20px rgba(245, 158, 11, 0.3)',
        premium: 'var(--shadow-premium)',
        'premium-lg': 'var(--shadow-premium-lg)',
        card: 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        dropdown: 'var(--shadow-dropdown)',
        modal: 'var(--shadow-modal)',
      },
      colors: {
        // Token-driven palette (maps directly to CSS variables)
        ocean: {
          50: 'hsl(var(--ocean-50))',
          100: 'hsl(var(--ocean-100))',
          200: 'hsl(var(--ocean-200))',
          300: 'hsl(var(--ocean-300))',
          400: 'hsl(var(--ocean-400))',
          500: 'hsl(var(--ocean-500))',
          600: 'hsl(var(--ocean-600))',
          700: 'hsl(var(--ocean-700))',
          800: 'hsl(var(--ocean-800))',
          900: 'hsl(var(--ocean-900))',
        },
        sand: {
          50: 'hsl(var(--sand-50))',
          100: 'hsl(var(--sand-100))',
          200: 'hsl(var(--sand-200))',
          300: 'hsl(var(--sand-300))',
          400: 'hsl(var(--sand-400))',
          500: 'hsl(var(--sand-500))',
          600: 'hsl(var(--sand-600))',
          700: 'hsl(var(--sand-700))',
          800: 'hsl(var(--sand-800))',
          900: 'hsl(var(--sand-900))',
        },
        sunset: {
          50: 'hsl(var(--sunset-50))',
          100: 'hsl(var(--sunset-100))',
          200: 'hsl(var(--sunset-200))',
          300: 'hsl(var(--sunset-300))',
          400: 'hsl(var(--sunset-400))',
          500: 'hsl(var(--sunset-500))',
          600: 'hsl(var(--sunset-600))',
          700: 'hsl(var(--sunset-700))',
          800: 'hsl(var(--sunset-800))',
          900: 'hsl(var(--sunset-900))',
        },
        olive: {
          50: 'hsl(var(--olive-50))',
          100: 'hsl(var(--olive-100))',
          200: 'hsl(var(--olive-200))',
          300: 'hsl(var(--olive-300))',
          400: 'hsl(var(--olive-400))',
          500: 'hsl(var(--olive-500))',
          600: 'hsl(var(--olive-600))',
          700: 'hsl(var(--olive-700))',
          800: 'hsl(var(--olive-800))',
          900: 'hsl(var(--olive-900))',
        },
        gold: {
          50: 'hsl(var(--gold-50))',
          100: 'hsl(var(--gold-100))',
          200: 'hsl(var(--gold-200))',
          300: 'hsl(var(--gold-300))',
          400: 'hsl(var(--gold-400))',
          500: 'hsl(var(--gold-500))',
          600: 'hsl(var(--gold-600))',
          700: 'hsl(var(--gold-700))',
          800: 'hsl(var(--gold-800))',
          900: 'hsl(var(--gold-900))',
        },
        brand: {
          DEFAULT: 'hsl(var(--color-primary-500))',
          dark: 'hsl(var(--color-primary-700))',
          50: 'hsl(var(--color-primary-50))',
          100: 'hsl(var(--color-primary-100))',
          200: 'hsl(var(--color-primary-200))',
          300: 'hsl(var(--color-primary-300))',
          400: 'hsl(var(--color-primary-400))',
          500: 'hsl(var(--color-primary-500))',
          600: 'hsl(var(--color-primary-600))',
          700: 'hsl(var(--color-primary-700))',
          800: 'hsl(var(--color-primary-800))',
          900: 'hsl(var(--color-primary-900))',
        },
        luxury: {
          50: '#FAF5FF',
          100: '#F3E8FF',
          200: '#E9D5FF',
          300: '#D8B4FE',
          400: '#C084FC',
          500: '#A855F7',
          600: '#9333EA',
          700: '#7C3AED',
          800: '#6B21A8',
          900: '#581C87',
        },
        success: {
          50: 'hsl(var(--color-success-50))',
          500: 'hsl(var(--color-success-500))',
          700: 'hsl(var(--color-success-700))',
        },
        warning: {
          50: 'hsl(var(--color-warning-50))',
          500: 'hsl(var(--color-warning-500))',
          700: 'hsl(var(--color-warning-700))',
        },
        info: {
          50: '#EFF6FF',
          100: '#DBEAFE',
          200: '#BFDBFE',
          300: '#93C5FD',
          400: '#60A5FA',
          500: '#3B82F6',
          600: '#2563EB',
          700: '#1D4ED8',
          800: '#1E40AF',
          900: '#1E3A8A',
        },
        error: {
          50: '#FEF2F2',
          100: '#FEE2E2',
          200: '#FECACA',
          300: '#FCA5A5',
          400: '#F87171',
          500: '#EF4444',
          600: '#DC2626',
          700: '#B91C1C',
          800: '#991B1B',
          900: '#7F1D1D',
        },
        glass: {
          light: 'hsla(var(--glass-bg))',
          dark: 'hsla(var(--glass-bg))',
          brand: 'hsla(var(--color-primary-500) / 0.15)',
        },
        ink: {
          700: '#334155',
          600: '#475569',
          500: '#64748B',
          400: '#94a3b8',
          300: '#cbd5e1',
        },
        // shadcn/ui colors using CSS variables + token-based semantic scales
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--color-primary-500))',
          50: 'hsl(var(--color-primary-50))',
          100: 'hsl(var(--color-primary-100))',
          200: 'hsl(var(--color-primary-200))',
          300: 'hsl(var(--color-primary-300))',
          400: 'hsl(var(--color-primary-400))',
          500: 'hsl(var(--color-primary-500))',
          600: 'hsl(var(--color-primary-600))',
          700: 'hsl(var(--color-primary-700))',
          800: 'hsl(var(--color-primary-800))',
          900: 'hsl(var(--color-primary-900))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        neutral: {
          DEFAULT: 'hsl(var(--color-neutral-500))',
          50: 'hsl(var(--color-neutral-50))',
          100: 'hsl(var(--color-neutral-100))',
          200: 'hsl(var(--color-neutral-200))',
          300: 'hsl(var(--color-neutral-300))',
          400: 'hsl(var(--color-neutral-400))',
          500: 'hsl(var(--color-neutral-500))',
          600: 'hsl(var(--color-neutral-600))',
          700: 'hsl(var(--color-neutral-700))',
          800: 'hsl(var(--color-neutral-800))',
          900: 'hsl(var(--color-neutral-900))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },      // For gradients used in the ribbon/spotlight
      backgroundImage: {
        'brand-ribbon': 'linear-gradient(90deg, #6CC24A 0%, #06b6d4 100%)',
        'brand-glass': 'linear-gradient(180deg, rgba(255,255,255,0.65) 0%, rgba(255,255,255,0.5) 100%)',
        'brand-premium': 'linear-gradient(90deg, #6CC24A 0%, #06b6d4 100%)',
        'gold-luxury': 'linear-gradient(90deg, #FBBF24 0%, #F59E0B 100%)',
        'glass-light': 'linear-gradient(180deg, rgba(255,255,255,0.7) 0%, rgba(255,255,255,0.5) 100%)',
        'glass-dark': 'linear-gradient(180deg, rgba(15,23,42,0.7) 0%, rgba(15,23,42,0.5) 100%)',
        'radial-brand': 'radial-gradient(circle, #6CC24A 0%, transparent 70%)',
        'mesh-premium': 'linear-gradient(45deg, #F3FAF1 25%, transparent 25%), linear-gradient(-45deg, #F3FAF1 25%, transparent 25%), linear-gradient(45deg, transparent 75%, #F3FAF1 75%), linear-gradient(-45deg, transparent 75%, #F3FAF1 75%)',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.4, 0.0, 0.2, 1)',
        snappy: 'cubic-bezier(0.4, 0.0, 0.6, 1)',
        bouncy: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        premium: 'cubic-bezier(0.25, 0.1, 0.25, 1)',
      },
      transitionDuration: {
        premium: '400ms',
        fast: '200ms',
        slow: '600ms',
      },
      spacing: {
        18: '4.5rem',
        22: '5.5rem',
        26: '6.5rem',
        'spacing-1': 'var(--spacing-1)',
        'spacing-2': 'var(--spacing-2)',
        'spacing-3': 'var(--spacing-3)',
        'spacing-4': 'var(--spacing-4)',
        'spacing-6': 'var(--spacing-6)',
        'spacing-8': 'var(--spacing-8)',
        'spacing-10': 'var(--spacing-10)',
        'spacing-12': 'var(--spacing-12)',
      },
      // Beautiful animations
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "slide-in-from-top": {
          from: { transform: "translateY(-100%)" },
          to: { transform: "translateY(0)" },
        },
        "slide-in-from-bottom": {
          from: { transform: "translateY(100%)" },
          to: { transform: "translateY(0)" },
        },
        "slide-in-from-left": {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-in-from-right": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-out": {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-1000px 0" },
          "100%": { backgroundPosition: "1000px 0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        'glow-pulse': {
          '0%, 100%': { opacity: '1', boxShadow: '0 0 20px rgba(108, 194, 74, 0.3)' },
          '50%': { opacity: '0.8', boxShadow: '0 0 30px rgba(108, 194, 74, 0.5)' },
        },
        'slide-up-fade': {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'scale-in-bounce': {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '50%': { transform: 'scale(1.02)', opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'shimmer-premium': {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "slide-in-from-top": "slide-in-from-top 0.3s ease-out",
        "slide-in-from-bottom": "slide-in-from-bottom 0.3s ease-out",
        "slide-in-from-left": "slide-in-from-left 0.3s ease-out",
        "slide-in-from-right": "slide-in-from-right 0.3s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "fade-out": "fade-out 0.3s ease-out",
        shimmer: "shimmer 2s linear infinite",
        float: "float 3s ease-in-out infinite",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'slide-up-fade': 'slide-up-fade 0.4s ease-out',
        'scale-in-bounce': 'scale-in-bounce 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'shimmer-premium': 'shimmer-premium 2.5s linear infinite',
      },
    },
  },
  plugins: [
    lineClamp,
    animate,
    heroui(),
    // Custom plugin for hiding scrollbars
    function ({ addUtilities }) {
      addUtilities({
        '.scrollbar-hide': {
          /* Firefox */
          'scrollbar-width': 'none',
          /* Safari and Chrome */
          '&::-webkit-scrollbar': {
            display: 'none',
          },
        },
      });
    },
  ],
}
