from django.core.management.base import BaseCommand
from django.db import transaction
from listings.models import Category, SubCategory


class Command(BaseCommand):
    help = "Seed the database with all marketplace categories and subcategories"

    @transaction.atomic
    def handle(self, *args, **options):
        self.stdout.write("🌱 Starting category seeding...")

        categories_data = [
            {
                "name": "Real Estate",
                "slug": "real-estate",
                "icon": "home",
                "color": "#FF6B6B",
                "is_bookable": True,
                "description": "Buy, sell, or rent properties including houses, apartments, villas, and commercial spaces",
                "schema": {
                    "fields": [
                        {
                            "name": "transaction_type",
                            "type": "select",
                            "label": "Transaction Type",
                            "choices": ["sale", "rent"],
                            "required": True,
                        },
                        {
                            "name": "property_type",
                            "type": "select",
                            "label": "Property Type",
                            "choices": [
                                "house",
                                "apartment",
                                "villa",
                                "bungalow",
                                "townhouse",
                                "penthouse",
                                "hotel",
                                "office",
                                "land",
                            ],
                            "required": True,
                        },
                        {
                            "name": "bedrooms",
                            "type": "number",
                            "label": "Bedrooms",
                            "min": 0,
                            "max": 20,
                            "required": False,
                        },
                        {
                            "name": "bathrooms",
                            "type": "number",
                            "label": "Bathrooms",
                            "min": 0,
                            "max": 10,
                            "required": False,
                        },
                        {
                            "name": "sqft",
                            "type": "number",
                            "label": "Square Feet",
                            "required": False,
                        },
                        {
                            "name": "furnished",
                            "type": "boolean",
                            "label": "Furnished",
                            "required": False,
                        },
                        {
                            "name": "rental_period",
                            "type": "select",
                            "label": "Rental Period",
                            "choices": ["daily", "weekly", "monthly", "yearly"],
                            "required_if": "transaction_type==rent",
                        },
                        {
                            "name": "year_built",
                            "type": "number",
                            "label": "Year Built",
                            "required": False,
                        },
                        {
                            "name": "property_condition",
                            "type": "select",
                            "label": "Condition",
                            "choices": ["excellent", "good", "fair", "needs_renovation"],
                            "required": False,
                        },
                    ]
                },
                "subcategories": [
                    {"name": "House", "slug": "house", "description": "Single-family home"},
                    {"name": "Apartment", "slug": "apartment", "description": "Flat or condo"},
                    {"name": "Villa", "slug": "villa", "description": "Luxury villa with amenities"},
                    {
                        "name": "Bungalow",
                        "slug": "bungalow",
                        "description": "Single-story residential",
                    },
                    {
                        "name": "Townhouse",
                        "slug": "townhouse",
                        "description": "Row-style home",
                    },
                    {"name": "Penthouse", "slug": "penthouse", "description": "Top-floor luxury"},
                    {
                        "name": "Hotel/Resort",
                        "slug": "hotel-resort",
                        "description": "Hospitality property",
                    },
                    {
                        "name": "Office/Commercial",
                        "slug": "office-commercial",
                        "description": "Business use property",
                    },
                    {
                        "name": "Land/Plot",
                        "slug": "land-plot",
                        "description": "Raw or developed land",
                    },
                ],
            },
            {
                "name": "Vehicles",
                "slug": "vehicles",
                "icon": "car",
                "color": "#4ECDC4",
                "is_bookable": True,
                "description": "Buy, sell, or rent vehicles including cars, motorcycles, and trucks",
                "schema": {
                    "fields": [
                        {
                            "name": "transaction_type",
                            "type": "select",
                            "label": "Transaction Type",
                            "choices": ["sale", "rental"],
                            "required": True,
                        },
                        {
                            "name": "vehicle_type",
                            "type": "select",
                            "label": "Vehicle Type",
                            "choices": [
                                "car",
                                "motorcycle",
                                "truck",
                                "bus",
                                "bicycle",
                                "scooter",
                                "boat",
                                "rv",
                            ],
                            "required": True,
                        },
                        {
                            "name": "make",
                            "type": "text",
                            "label": "Make/Brand",
                            "required": True,
                        },
                        {
                            "name": "model",
                            "type": "text",
                            "label": "Model",
                            "required": True,
                        },
                        {
                            "name": "year",
                            "type": "number",
                            "label": "Year",
                            "min": 1900,
                            "required": True,
                        },
                        {
                            "name": "mileage",
                            "type": "number",
                            "label": "Mileage (km)",
                            "required": False,
                        },
                        {
                            "name": "fuel_type",
                            "type": "select",
                            "label": "Fuel Type",
                            "choices": ["petrol", "diesel", "electric", "hybrid"],
                            "required": False,
                        },
                        {
                            "name": "transmission",
                            "type": "select",
                            "label": "Transmission",
                            "choices": ["manual", "automatic"],
                            "required": False,
                        },
                        {
                            "name": "condition",
                            "type": "select",
                            "label": "Condition",
                            "choices": ["excellent", "good", "fair", "needs_repair"],
                            "required": False,
                        },
                        {
                            "name": "rental_period",
                            "type": "select",
                            "label": "Rental Period",
                            "choices": ["daily", "weekly", "monthly"],
                            "required_if": "transaction_type==rental",
                        },
                    ]
                },
                "subcategories": [
                    {"name": "Car", "slug": "car", "description": "Sedan, SUV, hatchback"},
                    {
                        "name": "Motorcycle/Scooter",
                        "slug": "motorcycle-scooter",
                        "description": "Two-wheelers",
                    },
                    {"name": "Truck/Commercial", "slug": "truck-commercial", "description": "Commercial vehicles"},
                    {"name": "Bus/Coach", "slug": "bus-coach", "description": "Public transport"},
                    {"name": "Bicycle", "slug": "bicycle", "description": "Manual bicycles"},
                    {"name": "Electric Scooter", "slug": "electric-scooter", "description": "E-scooters"},
                    {"name": "Boat/Yacht", "slug": "boat-yacht", "description": "Watercraft"},
                    {"name": "RV/Campervan", "slug": "rv-campervan", "description": "Recreational vehicles"},
                ],
            },
            {
                "name": "Electronics",
                "slug": "electronics",
                "icon": "zap",
                "color": "#95E1D3",
                "is_bookable": False,
                "description": "Buy and sell electronics including phones, laptops, cameras, and gaming consoles",
                "schema": {
                    "fields": [
                        {
                            "name": "electronics_type",
                            "type": "select",
                            "label": "Product Type",
                            "choices": [
                                "mobile_phone",
                                "laptop",
                                "tablet",
                                "gaming_console",
                                "camera",
                                "audio",
                                "tv",
                                "printer",
                                "accessories",
                            ],
                            "required": True,
                        },
                        {
                            "name": "brand",
                            "type": "text",
                            "label": "Brand",
                            "required": True,
                        },
                        {
                            "name": "model",
                            "type": "text",
                            "label": "Model",
                            "required": True,
                        },
                        {
                            "name": "condition",
                            "type": "select",
                            "label": "Condition",
                            "choices": ["new", "like_new", "used", "refurbished"],
                            "required": True,
                        },
                        {
                            "name": "warranty_months",
                            "type": "number",
                            "label": "Warranty (months)",
                            "min": 0,
                            "required": False,
                        },
                        {
                            "name": "original_box",
                            "type": "boolean",
                            "label": "Original Box Included",
                            "required": False,
                        },
                        {
                            "name": "testing_status",
                            "type": "select",
                            "label": "Testing Status",
                            "choices": ["tested_working", "untested"],
                            "required": False,
                        },
                    ]
                },
                "subcategories": [
                    {"name": "Mobile Phones", "slug": "mobile-phones", "description": "Smartphones"},
                    {"name": "Computers/Laptops", "slug": "computers-laptops", "description": "Laptops and desktops"},
                    {"name": "Tablets", "slug": "tablets", "description": "iPad and Android tablets"},
                    {"name": "Gaming Consoles", "slug": "gaming-consoles", "description": "PS5, Xbox, Nintendo"},
                    {"name": "Cameras", "slug": "cameras", "description": "DSLR, mirrorless, compact"},
                    {"name": "Audio Equipment", "slug": "audio-equipment", "description": "Headphones, speakers"},
                    {"name": "TVs", "slug": "tvs", "description": "Smart TVs and displays"},
                    {"name": "Printers/Scanners", "slug": "printers-scanners", "description": "Office equipment"},
                    {"name": "Accessories", "slug": "accessories", "description": "Chargers, cables, cases"},
                ],
            },
            {
                "name": "Household Items",
                "slug": "household-items",
                "icon": "home",
                "color": "#FFD93D",
                "is_bookable": False,
                "description": "Buy and sell household items including furniture, appliances, and decor",
                "schema": {
                    "fields": [
                        {
                            "name": "item_type",
                            "type": "select",
                            "label": "Item Type",
                            "choices": [
                                "kitchen_appliances",
                                "refrigerator",
                                "washing_machine",
                                "furniture_bedroom",
                                "furniture_living_room",
                                "dining_sets",
                                "bedding",
                                "lighting",
                                "decor",
                            ],
                            "required": True,
                        },
                        {
                            "name": "condition",
                            "type": "select",
                            "label": "Condition",
                            "choices": ["new", "like_new", "used", "damaged_functional"],
                            "required": True,
                        },
                        {
                            "name": "material",
                            "type": "text",
                            "label": "Material",
                            "required": False,
                        },
                        {
                            "name": "color",
                            "type": "text",
                            "label": "Color",
                            "required": False,
                        },
                        {
                            "name": "age_years",
                            "type": "number",
                            "label": "Age (years)",
                            "required": False,
                        },
                        {
                            "name": "delivery_available",
                            "type": "boolean",
                            "label": "Delivery Available",
                            "required": False,
                        },
                    ]
                },
                "subcategories": [
                    {"name": "Kitchen Appliances", "slug": "kitchen-appliances", "description": "Kitchen equipment"},
                    {"name": "Refrigerators", "slug": "refrigerators", "description": "Fridges and freezers"},
                    {"name": "Washing Machines", "slug": "washing-machines", "description": "Laundry equipment"},
                    {"name": "Furniture - Bedroom", "slug": "furniture-bedroom", "description": "Bedroom furniture"},
                    {"name": "Furniture - Living Room", "slug": "furniture-living-room", "description": "Living room furniture"},
                    {"name": "Dining Sets", "slug": "dining-sets", "description": "Dining furniture"},
                    {"name": "Bedding", "slug": "bedding", "description": "Mattresses, pillows, duvets"},
                    {"name": "Lighting", "slug": "lighting", "description": "Lamps and fixtures"},
                    {"name": "Decor & Accessories", "slug": "decor-accessories", "description": "Home decor"},
                ],
            },
            {
                "name": "Products",
                "slug": "products",
                "icon": "shopping-bag",
                "color": "#A8E6CF",
                "is_bookable": False,
                "description": "General products including clothing, books, sports equipment, and more",
                "schema": {
                    "fields": [
                        {
                            "name": "product_type",
                            "type": "select",
                            "label": "Product Type",
                            "choices": [
                                "books",
                                "clothing",
                                "shoes",
                                "sports_equipment",
                                "toys_games",
                                "beauty_personal_care",
                                "pet_supplies",
                                "tools_hardware",
                            ],
                            "required": True,
                        },
                        {
                            "name": "condition",
                            "type": "select",
                            "label": "Condition",
                            "choices": ["new", "like_new", "used", "damaged"],
                            "required": True,
                        },
                        {
                            "name": "size",
                            "type": "text",
                            "label": "Size (if applicable)",
                            "required": False,
                        },
                        {
                            "name": "brand",
                            "type": "text",
                            "label": "Brand",
                            "required": False,
                        },
                    ]
                },
                "subcategories": [
                    {"name": "Books", "slug": "books", "description": "All genres"},
                    {"name": "Clothing & Fashion", "slug": "clothing-fashion", "description": "Apparel"},
                    {"name": "Shoes & Footwear", "slug": "shoes-footwear", "description": "Footwear"},
                    {"name": "Sports Equipment", "slug": "sports-equipment", "description": "Sports gear"},
                    {"name": "Toys & Games", "slug": "toys-games", "description": "Toys and board games"},
                    {"name": "Beauty & Personal Care", "slug": "beauty-personal-care", "description": "Beauty products"},
                    {"name": "Pet Supplies", "slug": "pet-supplies", "description": "Pet products"},
                    {"name": "Tools & Hardware", "slug": "tools-hardware", "description": "Tools and hardware"},
                ],
            },
            {
                "name": "Events",
                "slug": "events",
                "icon": "calendar",
                "color": "#F38181",
                "is_bookable": True,
                "description": "Browse and book event tickets including conferences, concerts, and parties",
                "schema": {
                    "fields": [
                        {
                            "name": "event_type",
                            "type": "select",
                            "label": "Event Type",
                            "choices": [
                                "conference",
                                "party",
                                "concert",
                                "sports",
                                "art_workshop",
                                "fitness",
                                "wellness",
                                "educational",
                                "networking",
                                "festival",
                            ],
                            "required": True,
                        },
                        {
                            "name": "event_date",
                            "type": "date",
                            "label": "Event Date",
                            "required": True,
                        },
                        {
                            "name": "event_time",
                            "type": "time",
                            "label": "Event Time",
                            "required": True,
                        },
                        {
                            "name": "duration_hours",
                            "type": "number",
                            "label": "Duration (hours)",
                            "required": False,
                        },
                        {
                            "name": "capacity",
                            "type": "number",
                            "label": "Capacity",
                            "required": True,
                        },
                        {
                            "name": "online_or_in_person",
                            "type": "select",
                            "label": "Format",
                            "choices": ["in_person", "online", "hybrid"],
                            "required": True,
                        },
                        {
                            "name": "meeting_link",
                            "type": "text",
                            "label": "Meeting Link (if online)",
                            "required_if": "online_or_in_person==online",
                        },
                        {
                            "name": "registration_deadline",
                            "type": "date",
                            "label": "Registration Deadline",
                            "required": False,
                        },
                    ]
                },
                "subcategories": [
                    {"name": "Conference/Workshop", "slug": "conference-workshop", "description": "Professional events"},
                    {"name": "Party/Social", "slug": "party-social", "description": "Social gatherings"},
                    {"name": "Concert/Music", "slug": "concert-music", "description": "Music events"},
                    {"name": "Sports Event", "slug": "sports-event", "description": "Sports competitions"},
                    {"name": "Art/Creative Workshop", "slug": "art-creative-workshop", "description": "Creative workshops"},
                    {"name": "Fitness Class", "slug": "fitness-class", "description": "Fitness events"},
                    {"name": "Wellness/Spa", "slug": "wellness-spa", "description": "Wellness events"},
                    {"name": "Educational Course", "slug": "educational-course", "description": "Learning events"},
                    {"name": "Networking Event", "slug": "networking-event", "description": "Professional networking"},
                    {"name": "Festival/Fair", "slug": "festival-fair", "description": "Large gatherings"},
                ],
            },
            {
                "name": "Activities",
                "slug": "activities",
                "icon": "activity",
                "color": "#F6A192",
                "is_bookable": True,
                "description": "Book classes and activities including fitness, dance, yoga, music lessons, and more",
                "schema": {
                    "fields": [
                        {
                            "name": "activity_type",
                            "type": "select",
                            "label": "Activity Type",
                            "choices": [
                                "fitness_wellness",
                                "dance",
                                "yoga",
                                "swimming",
                                "martial_arts",
                                "sports_training",
                                "art_crafts",
                                "music_lessons",
                                "language_classes",
                                "cooking",
                                "photography",
                                "sports_recreation",
                                "outdoor_adventures",
                                "gaming",
                                "hobby_clubs",
                                "personal_training",
                                "pilates",
                                "crossfit",
                                "boxing",
                                "corporate_wellness",
                                "spa_relaxation",
                                "workshop_seminar",
                                "kids_activities",
                                "team_building",
                            ],
                            "required": True,
                        },
                        {
                            "name": "skill_level",
                            "type": "select",
                            "label": "Skill Level",
                            "choices": ["beginner", "intermediate", "advanced", "all_levels"],
                            "required": True,
                        },
                        {
                            "name": "schedule_type",
                            "type": "select",
                            "label": "Schedule Type",
                            "choices": ["single_session", "recurring", "course"],
                            "required": True,
                        },
                        {
                            "name": "start_date",
                            "type": "date",
                            "label": "Start Date",
                            "required": True,
                        },
                        {
                            "name": "start_time",
                            "type": "time",
                            "label": "Start Time",
                            "required": True,
                        },
                        {
                            "name": "class_duration_minutes",
                            "type": "number",
                            "label": "Duration (minutes)",
                            "required": True,
                        },
                        {
                            "name": "capacity",
                            "type": "number",
                            "label": "Capacity",
                            "required": True,
                        },
                        {
                            "name": "online_or_in_person",
                            "type": "select",
                            "label": "Format",
                            "choices": ["in_person", "online", "hybrid"],
                            "required": True,
                        },
                        {
                            "name": "equipment_provided",
                            "type": "boolean",
                            "label": "Equipment Provided",
                            "required": False,
                        },
                        {
                            "name": "instructor_name",
                            "type": "text",
                            "label": "Instructor Name",
                            "required": False,
                        },
                    ]
                },
                "subcategories": [
                    {"name": "Fitness & Wellness", "slug": "fitness-wellness", "description": "General fitness"},
                    {"name": "Dance Classes", "slug": "dance-classes", "description": "Various dance styles"},
                    {"name": "Yoga & Meditation", "slug": "yoga-meditation", "description": "Yoga and mindfulness"},
                    {"name": "Swimming", "slug": "swimming", "description": "Swimming lessons"},
                    {"name": "Martial Arts", "slug": "martial-arts", "description": "Combat sports"},
                    {"name": "Sports Training", "slug": "sports-training", "description": "Sports coaching"},
                    {"name": "Art & Crafts", "slug": "art-crafts", "description": "Creative workshops"},
                    {"name": "Music Lessons", "slug": "music-lessons", "description": "Instrument training"},
                    {"name": "Language Classes", "slug": "language-classes", "description": "Language learning"},
                    {"name": "Cooking Classes", "slug": "cooking-classes", "description": "Culinary classes"},
                    {"name": "Photography Workshop", "slug": "photography-workshop", "description": "Photography training"},
                    {"name": "Sports Recreation", "slug": "sports-recreation", "description": "Casual sports"},
                    {"name": "Outdoor Adventures", "slug": "outdoor-adventures", "description": "Adventure activities"},
                    {"name": "Gaming & Esports", "slug": "gaming-esports", "description": "Gaming activities"},
                    {"name": "Hobby Clubs", "slug": "hobby-clubs", "description": "Interest-based groups"},
                    {"name": "Personal Training", "slug": "personal-training", "description": "One-on-one training"},
                    {"name": "Pilates", "slug": "pilates", "description": "Pilates classes"},
                    {"name": "CrossFit", "slug": "crossfit", "description": "CrossFit training"},
                    {"name": "Boxing/Kickboxing", "slug": "boxing-kickboxing", "description": "Boxing training"},
                    {"name": "Corporate Wellness", "slug": "corporate-wellness", "description": "Team wellness"},
                    {"name": "Spa & Relaxation", "slug": "spa-relaxation", "description": "Relaxation activities"},
                    {"name": "Workshop/Seminar", "slug": "workshop-seminar", "description": "Educational workshops"},
                    {"name": "Kids Activities", "slug": "kids-activities", "description": "Activities for children"},
                    {"name": "Team Building", "slug": "team-building", "description": "Team activities"},
                ],
            },
            {
                "name": "Services",
                "slug": "services",
                "icon": "briefcase",
                "color": "#AA96DA",
                "is_bookable": True,
                "description": "Book professional services including home services, legal, design, beauty, and more",
                "schema": {
                    "fields": [
                        {
                            "name": "service_type",
                            "type": "select",
                            "label": "Service Type",
                            "choices": [
                                "home_services",
                                "plumbing",
                                "electrical",
                                "carpentry",
                                "cleaning",
                                "painting",
                                "hvac",
                                "pest_control",
                                "car_wash",
                                "auto_repair",
                                "legal",
                                "accounting",
                                "it_support",
                                "tutoring",
                                "photography",
                                "videography",
                                "web_design",
                                "graphic_design",
                                "translation",
                                "fitness_coaching",
                                "nutritionist",
                                "mental_health",
                                "beauty_services",
                                "massage",
                                "veterinary",
                                "event_planning",
                                "interior_design",
                                "landscaping",
                            ],
                            "required": True,
                        },
                        {
                            "name": "service_availability",
                            "type": "select",
                            "label": "Availability",
                            "choices": ["hourly", "flat_rate", "project_based"],
                            "required": True,
                        },
                        {
                            "name": "service_area",
                            "type": "text",
                            "label": "Service Area",
                            "required": False,
                        },
                        {
                            "name": "response_time_hours",
                            "type": "number",
                            "label": "Response Time (hours)",
                            "required": False,
                        },
                        {
                            "name": "emergency_available",
                            "type": "boolean",
                            "label": "Emergency Services Available",
                            "required": False,
                        },
                        {
                            "name": "years_experience",
                            "type": "number",
                            "label": "Years of Experience",
                            "required": False,
                        },
                        {
                            "name": "certification_license",
                            "type": "text",
                            "label": "Certifications/License",
                            "required": False,
                        },
                    ]
                },
                "subcategories": [
                    {"name": "Home Services", "slug": "home-services", "description": "Repair and maintenance"},
                    {"name": "Plumbing", "slug": "plumbing", "description": "Plumbing services"},
                    {"name": "Electrical", "slug": "electrical", "description": "Electrical services"},
                    {"name": "Carpentry/Handyman", "slug": "carpentry-handyman", "description": "Carpentry work"},
                    {"name": "Cleaning Services", "slug": "cleaning-services", "description": "Cleaning services"},
                    {"name": "Painting & Decoration", "slug": "painting-decoration", "description": "Painting services"},
                    {"name": "HVAC Services", "slug": "hvac-services", "description": "Heating and cooling"},
                    {"name": "Pest Control", "slug": "pest-control", "description": "Pest control services"},
                    {"name": "Car Wash & Detailing", "slug": "car-wash-detailing", "description": "Car services"},
                    {"name": "Auto Repair", "slug": "auto-repair", "description": "Vehicle repair"},
                    {"name": "Legal Services", "slug": "legal-services", "description": "Legal advice"},
                    {"name": "Accounting/Tax", "slug": "accounting-tax", "description": "Financial services"},
                    {"name": "IT Support", "slug": "it-support", "description": "Technology support"},
                    {"name": "Tutoring/Education", "slug": "tutoring-education", "description": "Educational services"},
                    {"name": "Photography Services", "slug": "photography-services", "description": "Photography"},
                    {"name": "Videography", "slug": "videography", "description": "Video production"},
                    {"name": "Web Design/Development", "slug": "web-design-development", "description": "Web services"},
                    {"name": "Graphic Design", "slug": "graphic-design", "description": "Design services"},
                    {"name": "Translation Services", "slug": "translation-services", "description": "Translation"},
                    {"name": "Fitness Coaching", "slug": "fitness-coaching", "description": "Fitness training"},
                    {"name": "Nutritionist/Dietitian", "slug": "nutritionist-dietitian", "description": "Nutrition services"},
                    {"name": "Mental Health Counseling", "slug": "mental-health-counseling", "description": "Counseling services"},
                    {"name": "Beauty Services", "slug": "beauty-services", "description": "Beauty treatments"},
                    {"name": "Massage Therapy", "slug": "massage-therapy", "description": "Massage services"},
                    {"name": "Veterinary Services", "slug": "veterinary-services", "description": "Pet care"},
                    {"name": "Event Planning", "slug": "event-planning", "description": "Event services"},
                    {"name": "Interior Design", "slug": "interior-design", "description": "Design services"},
                    {"name": "Landscaping/Gardening", "slug": "landscaping-gardening", "description": "Outdoor services"},
                ],
            },
            {
                "name": "Appointments",
                "slug": "appointments",
                "icon": "calendar",
                "color": "#FECDC3",
                "is_bookable": True,
                "description": "Book time-slot appointments including hair, dental, medical, massage, and more",
                "schema": {
                    "fields": [
                        {
                            "name": "appointment_type",
                            "type": "select",
                            "label": "Appointment Type",
                            "choices": [
                                "hair_services",
                                "dental",
                                "medical",
                                "haircut_beard",
                                "manicure_pedicure",
                                "massage",
                                "spa_facial",
                                "eye_exam",
                                "veterinary",
                                "therapy",
                                "physical_therapy",
                                "tattoo",
                                "piercing",
                                "fitness_consultation",
                                "car_service",
                            ],
                            "required": True,
                        },
                        {
                            "name": "slot_duration_minutes",
                            "type": "number",
                            "label": "Appointment Duration (minutes)",
                            "required": True,
                        },
                        {
                            "name": "professional_name",
                            "type": "text",
                            "label": "Professional Name",
                            "required": False,
                        },
                        {
                            "name": "telehealth_available",
                            "type": "boolean",
                            "label": "Telehealth Available",
                            "required": False,
                        },
                        {
                            "name": "deposit_required",
                            "type": "number",
                            "label": "Deposit Required",
                            "required": False,
                        },
                        {
                            "name": "cancellation_policy_days",
                            "type": "number",
                            "label": "Cancellation Policy (days notice)",
                            "required": False,
                        },
                    ]
                },
                "subcategories": [
                    {"name": "Hair Services", "slug": "hair-services", "description": "Hair styling and treatment"},
                    {"name": "Dental", "slug": "dental", "description": "Dental appointments"},
                    {"name": "Medical Checkup", "slug": "medical-checkup", "description": "Doctor appointments"},
                    {"name": "Haircut/Beard Trim", "slug": "haircut-beard-trim", "description": "Barber services"},
                    {"name": "Manicure/Pedicure", "slug": "manicure-pedicure", "description": "Nail services"},
                    {"name": "Massage", "slug": "massage", "description": "Massage therapy"},
                    {"name": "Spa/Facial", "slug": "spa-facial", "description": "Spa treatments"},
                    {"name": "Eye Exam", "slug": "eye-exam", "description": "Optometry services"},
                    {"name": "Veterinary Checkup", "slug": "veterinary-checkup", "description": "Pet vet"},
                    {"name": "Therapy/Counseling", "slug": "therapy-counseling", "description": "Mental health"},
                    {"name": "Physical Therapy", "slug": "physical-therapy", "description": "PT services"},
                    {"name": "Tattoo Appointment", "slug": "tattoo-appointment", "description": "Tattoo services"},
                    {"name": "Piercing Appointment", "slug": "piercing-appointment", "description": "Piercing services"},
                    {"name": "Fitness Consultation", "slug": "fitness-consultation", "description": "Fitness advice"},
                    {"name": "Car Service Appointment", "slug": "car-service-appointment", "description": "Car maintenance"},
                ],
            },
        ]

        # Create categories and subcategories
        for cat_data in categories_data:
            subcats_data = cat_data.pop("subcategories", [])
            
            category, created = Category.objects.get_or_create(
                slug=cat_data["slug"],
                defaults=cat_data
            )
            
            status = "✅ Created" if created else "⏭️ Already exists"
            self.stdout.write(f"  {status}: {category.name}")

            # Create subcategories
            for subcat_data in subcats_data:
                subcat, sub_created = SubCategory.objects.get_or_create(
                    category=category,
                    slug=subcat_data["slug"],
                    defaults={
                        "name": subcat_data["name"],
                        "description": subcat_data.get("description", ""),
                    }
                )
                if sub_created:
                    self.stdout.write(f"    ✓ {subcat.name}")

        self.stdout.write(self.style.SUCCESS("\n✅ Category seeding complete!"))
