# Generated by Django 5.0.4 on 2025-11-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_buyerrequest_broadcastmessage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="booking",
            new_name="listings_bo_user_id_f12e91_idx",
            old_name="listings_bo_user_id_3a8f9c_idx",
        ),
        migrations.RenameIndex(
            model_name="booking",
            new_name="listings_bo_listing_be16bb_idx",
            old_name="listings_bo_listing_b7e4d2_idx",
        ),
        migrations.RenameIndex(
            model_name="booking",
            new_name="listings_bo_check_i_337c35_idx",
            old_name="listings_bo_check_i_5f8a1e_idx",
        ),
        migrations.RenameIndex(
            model_name="broadcastmessage",
            new_name="listings_br_seller__06c32e_idx",
            old_name="listings_br_seller__6f7c8d_idx",
        ),
        migrations.RenameIndex(
            model_name="broadcastmessage",
            new_name="listings_br_categor_b081ac_idx",
            old_name="listings_br_categor_9e8a1c_idx",
        ),
        migrations.RenameIndex(
            model_name="broadcastmessage",
            new_name="listings_br_publish_ea46c9_idx",
            old_name="listings_br_publish_2b3d4f_idx",
        ),
        migrations.RenameIndex(
            model_name="buyerrequest",
            new_name="listings_bu_categor_f1a770_idx",
            old_name="listings_bu_categor_8a1d4e_idx",
        ),
        migrations.RenameIndex(
            model_name="buyerrequest",
            new_name="listings_bu_buyer_i_24a6b9_idx",
            old_name="listings_bu_buyer_i_9c2e1f_idx",
        ),
        migrations.RenameIndex(
            model_name="buyerrequest",
            new_name="listings_bu_is_fulf_8cb24b_idx",
            old_name="listings_bu_is_fulf_3d4a5b_idx",
        ),
        migrations.RenameIndex(
            model_name="sellerprofile",
            new_name="listings_se_verifie_b34c73_idx",
            old_name="listings_se_verifie_a8f4d2_idx",
        ),
        migrations.RenameIndex(
            model_name="sellerprofile",
            new_name="listings_se_user_id_8a0e4d_idx",
            old_name="listings_se_user_id_7c5e1b_idx",
        ),
    ]
