# Generated by Django 5.0.4 on 2025-11-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0006_rename_listings_bo_user_id_3a8f9c_idx_listings_bo_user_id_f12e91_idx_and_more",
        ),
    ]

    operations = []
