# Generated by Django 5.0.4 on 2025-11-16 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_sellerprofile_storefront_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicelisting",
            name="service_subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_listings",
                to="listings.subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
