"""
Prometheus Metrics for Real Estate Agent

Counters, histograms, and gauges for observability.
"""

from prometheus_client import Counter, Histogram, Gauge
import logging

logger = logging.getLogger(__name__)

# ============================================================================
# REAL ESTATE AGENT METRICS
# ============================================================================

# Counters
re_agent_act_total = Counter(
    're_agent_act_total',
    'Total number of agent actions by type',
    ['act']  # ASK_SLOT, ACK_AND_SEARCH, SEARCH_AND_RECOMMEND, CLARIFY, ESCALATE
)

re_json_parse_fail_total = Counter(
    're_json_parse_fail_total',
    'Total JSON parse failures from LLM response'
)

re_card_emitted_total = Counter(
    're_card_emitted_total',
    'Total recommendation cards emitted',
    ['variant']  # short_term, long_term
)

# RecItem v1 Card Generation Metrics
re_cards_generated_total = Counter(
    're_cards_generated_total',
    'Total RecItem cards generated by format_v1_listing_for_card',
    ['rent_type']  # daily, long_term, sale, project
)

re_cards_without_images_total = Counter(
    're_cards_without_images_total',
    'Total RecItem cards generated without hero image',
    ['rent_type']
)

# RecItem v1 Booking API Metrics
re_availability_checks_total = Counter(
    're_availability_checks_total',
    'Total availability check requests',
    ['result']  # available, unavailable, error
)

re_booking_requests_total = Counter(
    're_booking_requests_total',
    'Total booking/tenancy creation requests',
    ['result', 'rent_type']  # result: success, conflict, error; rent_type: daily, long_term
)

re_router_pinned_total = Counter(
    're_router_pinned_total',
    'Total times router was pinned to real_estate_agent',
    ['reason']  # slot_filling_guard, refinement, continuity
)

re_handoff_total = Counter(
    're_handoff_total',
    'Total domain handoffs from real_estate_agent',
    ['to_domain']  # marketplace_agent, general_conversation_agent, etc.
)

re_error_total = Counter(
    're_error_total',
    'Total errors by type',
    ['type']  # json_contract, search_timeout, card_emit, circuit_open
)

# Histograms (timings in milliseconds)
re_prompt_end_to_end_ms = Histogram(
    're_prompt_end_to_end_ms',
    'End-to-end time from prompt render to JSON parse (ms)',
    buckets=[50, 100, 200, 400, 800, 1200, 2000, 5000]
)

re_backend_search_ms = Histogram(
    're_backend_search_ms',
    'Backend search API call duration (ms)',
    buckets=[50, 100, 200, 400, 600, 800, 1000, 2000]
)

re_turn_total_ms = Histogram(
    're_turn_total_ms',
    'Total turn processing time (ms)',
    buckets=[100, 300, 600, 900, 1200, 1800, 3000, 5000]
)

# Gauges
re_circuit_breaker_state = Gauge(
    're_circuit_breaker_state',
    'Circuit breaker state (0=closed, 1=open)',
    ['service']  # backend_search
)

re_active_slots_gauge = Gauge(
    're_active_slots_gauge',
    'Number of active slot-filling sessions'
)

# v2.0: Adaptive Slot-Filling Metrics
re_slots_prompted_total = Counter(
    're_slots_prompted_total',
    'Total times each slot was explicitly asked',
    ['slot']  # location, budget, bedrooms, etc.
)

re_slots_skipped_total = Counter(
    're_slots_skipped_total',
    'Total times each slot was skipped after max attempts',
    ['slot']
)

re_inference_success_total = Counter(
    're_inference_success_total',
    'Total successful slot inferences',
    ['slot', 'source']  # source: llm, heuristic
)

re_inference_fail_total = Counter(
    're_inference_fail_total',
    'Total failed slot inference attempts',
    ['slot']
)

re_user_abandon_rate = Counter(
    're_user_abandon_rate',
    'Sessions abandoned during slot-filling stage'
)

re_slot_confidence_gauge = Gauge(
    're_slot_confidence_gauge',
    'Current confidence score for inferred slots',
    ['slot']
)


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def record_agent_act(act: str):
    """Record agent action."""
    re_agent_act_total.labels(act=act).inc()


def record_json_parse_fail():
    """Record JSON parse failure."""
    re_json_parse_fail_total.inc()


def record_card_emitted(variant: str):
    """Record recommendation card emission."""
    re_card_emitted_total.labels(variant=variant).inc()


def record_router_pinned(reason: str):
    """Record router pinning event."""
    re_router_pinned_total.labels(reason=reason).inc()


def record_handoff(to_domain: str):
    """Record domain handoff."""
    re_handoff_total.labels(to_domain=to_domain).inc()


def record_error(error_type: str):
    """Record error by type."""
    re_error_total.labels(type=error_type).inc()


def record_prompt_duration(duration_ms: float):
    """Record prompt end-to-end duration."""
    re_prompt_end_to_end_ms.observe(duration_ms)


def record_search_duration(duration_ms: float):
    """Record backend search duration."""
    re_backend_search_ms.observe(duration_ms)


def record_turn_duration(duration_ms: float):
    """Record total turn duration."""
    re_turn_total_ms.observe(duration_ms)


def set_circuit_breaker_state(service: str, is_open: bool):
    """Set circuit breaker state."""
    re_circuit_breaker_state.labels(service=service).set(1 if is_open else 0)


# v2.0: Adaptive Slot-Filling Helper Functions
def record_slot_prompted(slot: str):
    """Record that a slot was explicitly asked."""
    re_slots_prompted_total.labels(slot=slot).inc()


def record_slot_skipped(slot: str):
    """Record that a slot was skipped after max attempts."""
    re_slots_skipped_total.labels(slot=slot).inc()


def record_inference_success(slot: str, source: str):
    """
    Record successful slot inference.

    Args:
        slot: Slot name (e.g., "location", "budget")
        source: Inference source ("llm" or "heuristic")
    """
    re_inference_success_total.labels(slot=slot, source=source).inc()


def record_inference_fail(slot: str):
    """Record failed slot inference attempt."""
    re_inference_fail_total.labels(slot=slot).inc()


def record_user_abandon():
    """Record session abandonment during slot-filling."""
    re_user_abandon_rate.inc()


def set_slot_confidence(slot: str, confidence: float):
    """Set current confidence score for inferred slot."""
    re_slot_confidence_gauge.labels(slot=slot).set(confidence)


# RecItem v1 Helper Functions
def record_card_generated(rent_type: str, has_image: bool):
    """
    Record RecItem card generation.

    Args:
        rent_type: Rental type (daily, long_term, sale, project)
        has_image: Whether hero image URL was available
    """
    re_cards_generated_total.labels(rent_type=rent_type).inc()
    if not has_image:
        re_cards_without_images_total.labels(rent_type=rent_type).inc()


def record_availability_check(result: str):
    """
    Record availability check result.

    Args:
        result: Check result (available, unavailable, error)
    """
    re_availability_checks_total.labels(result=result).inc()


def record_booking_request(result: str, rent_type: str):
    """
    Record booking/tenancy creation request.

    Args:
        result: Request result (success, conflict, error)
        rent_type: Rental type (daily, long_term)
    """
    re_booking_requests_total.labels(result=result, rent_type=rent_type).inc()


logger.info("[Metrics] Real Estate Agent metrics registered")
