# Generated by Django 5.0.4 on 2025-11-12 10:20

import django.utils.timezone
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="AgentBroadcast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "seller_id",
                    models.CharField(
                        blank=True,
                        help_text="Target seller/business identifier",
                        max_length=64,
                    ),
                ),
                (
                    "medium",
                    models.CharField(help_text="email | sms | whatsapp", max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="pending | sent | failed | responded | retrying",
                        max_length=32,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response_log",
                    models.JSONField(
                        default=dict,
                        help_text="Optional payload of provider responses / metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentBroadcastV2",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "seller_id",
                    models.CharField(
                        blank=True,
                        help_text="Target seller/business identifier",
                        max_length=64,
                    ),
                ),
                (
                    "medium",
                    models.CharField(help_text="email | sms | whatsapp", max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="pending | sent | failed | responded | retrying",
                        max_length=32,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response_log",
                    models.JSONField(
                        default=dict,
                        help_text="Optional payload of provider responses / metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent Broadcast V2",
                "verbose_name_plural": "Agent Broadcasts V2",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApproveBroadcast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_seller_count",
                    models.IntegerField(help_text="Number of sellers to be contacted"),
                ),
                (
                    "seller_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of seller IDs targeted for this broadcast",
                    ),
                ),
                (
                    "medium",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                        ],
                        default="whatsapp",
                        help_text="Communication medium for broadcast",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired (24h timeout)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "approval_notes",
                    models.TextField(
                        blank=True,
                        help_text="Business user notes on approval/rejection decision",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_approve_broadcasts", "Can approve RFQ broadcasts"),
                    ("can_reject_broadcasts", "Can reject RFQ broadcasts"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("preferred_date", models.DateTimeField()),
                ("preferred_time", models.TimeField()),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Additional message for the agent"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("agent_response", models.TextField(blank=True)),
                (
                    "agent_available_times",
                    models.JSONField(
                        default=list, help_text="Available time slots from agent"
                    ),
                ),
                (
                    "agent_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes from agent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("telegram_handle", models.CharField(blank=True, max_length=255)),
                ("last_contacted", models.DateTimeField(blank=True, null=True)),
                ("contact_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(auto_now=True)),
                ("language", models.CharField(default="en", max_length=5)),
            ],
            options={
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        help_text="UUID identifying this conversation thread (LangGraph checkpoint key)",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Active thread for this user (one active thread per user)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DemandLead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact_info", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extracted_criteria",
                    models.JSONField(
                        default=dict,
                        help_text="Structured search/lead criteria extracted by NLU",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("broadcasted", "Broadcasted"),
                            ("responded", "Responded"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "intent_type",
                    models.CharField(
                        choices=[
                            ("short_term", "Short Term"),
                            ("long_term", "Long Term"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "sellers_contacted",
                    models.JSONField(
                        default=list,
                        help_text="Audit log of sellers contacted for this request",
                    ),
                ),
                (
                    "handle_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes / BI for this request"
                    ),
                ),
                ("source_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "source_provider",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("twitter", "Twitter"),
                            ("linkedin", "LinkedIn"),
                            ("reddit", "Reddit"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True, null=True)),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("raw_content", models.TextField(blank=True, null=True)),
                ("keywords_detected", models.JSONField(default=list)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("structured_lead", models.JSONField(default=dict)),
                ("is_processed", models.BooleanField(default=False)),
            ],
            options={
                "permissions": [
                    ("can_broadcast_to_all_sellers", "Can broadcast to all sellers")
                ],
            },
        ),
        migrations.CreateModel(
            name="FailedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("args", models.JSONField()),
                ("exception", models.TextField()),
                ("failed_at", models.DateTimeField(auto_now_add=True)),
                ("retried_at", models.DateTimeField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-failed_at"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField(default=dict)),
                ("enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100)),
                ("language", models.CharField(default="en", max_length=5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LinkSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("broadcast_request", "Broadcast Request"),
                            ("seller_response", "Seller Response"),
                            ("user", "User Message"),
                            ("assistant", "Assistant Message"),
                            ("system", "System Message"),
                        ],
                        default="user",
                        help_text="Message classification",
                        max_length=20,
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(
                        db_index=True,
                        default="legacy-conv",
                        help_text="Links all messages in a thread (non-null for ALL types) [Q20]",
                        max_length=255,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Primary message text or summary"),
                ),
                (
                    "demand_lead_id",
                    models.CharField(
                        blank=True,
                        help_text="Foreign key to DemandLead (for Flow 2 messages)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "client_msg_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Client-generated UUID for idempotency (prevents duplicate processing on network retry)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_unread",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unread status (excludes system messages from badge count) [Q11]",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when marked as read", null=True
                    ),
                ),
                (
                    "broadcast_metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Structured criteria for broadcast_request (gatekept: location, budget, category, duration) [Q7, Q9]",
                        null=True,
                    ),
                ),
                (
                    "offer_metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Seller offer details for seller_response (price, availability, photos, details, links) [Q19c]",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreferenceExtractionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("thread_id", models.CharField(db_index=True, max_length=255)),
                ("message_id", models.UUIDField(db_index=True)),
                ("utterance", models.TextField()),
                ("extracted_preferences", models.JSONField(default=list)),
                ("confidence_scores", models.JSONField(default=dict)),
                (
                    "extraction_method",
                    models.CharField(
                        choices=[
                            ("llm", "LLM (OpenAI)"),
                            ("rule", "Rule-based"),
                            ("hybrid", "Hybrid (LLM + Rules)"),
                            ("fallback", "Fallback Only"),
                        ],
                        max_length=50,
                    ),
                ),
                ("llm_reasoning", models.TextField(blank=True)),
                ("contradictions_detected", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processing_time_ms", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "preference_extraction_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PROPERTY", "Property"),
                            ("VEHICLE", "Vehicle"),
                            ("GENERAL_PRODUCT", "General Product"),
                            ("SERVICE", "Service"),
                            ("KNOWLEDGE_QUERY", "Knowledge Query"),
                            ("OUT_OF_SCOPE", "Out of Scope"),
                        ],
                        max_length=32,
                    ),
                ),
                ("subcategory", models.CharField(blank=True, max_length=64)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "budget_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("budget_currency", models.CharField(blank=True, max_length=8)),
                (
                    "attributes",
                    models.JSONField(
                        default=dict,
                        help_text="Flexible attributes for domain-specific needs",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        help_text="User-provided contact (tokenized/redacted in serializers)",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("pending_approval", "Pending Approval"),
                            ("broadcasted", "Broadcasted"),
                            ("responded", "Responded"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Request",
                "verbose_name_plural": "Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=255)),
                ("name_tr", models.CharField(blank=True, max_length=255)),
                ("name_ru", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_info", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("service_type", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("real_estate", "Real Estate"),
                            ("services", "Services"),
                            ("lifestyle", "Lifestyle"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("preference_type", models.CharField(db_index=True, max_length=50)),
                ("value", models.JSONField(help_text="Normalized structured value")),
                (
                    "raw_value",
                    models.TextField(
                        blank=True, help_text="Original utterance (PII-redacted)"
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("explicit", "Explicitly Stated"),
                            ("inferred", "Inferred from Context"),
                            ("behavior", "Learned from Behavior"),
                        ],
                        max_length=50,
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_decayed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("use_count", models.IntegerField(default=0)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("schema_version", models.IntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "user_preferences",
                "ordering": ["-confidence", "-last_used_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("bio", models.TextField(blank=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("tr", "Turkish"),
                            ("ru", "Russian"),
                            ("pl", "Polish"),
                        ],
                        default="en",
                        help_text="User preferred language for chat",
                        max_length=10,
                    ),
                ),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="light",
                        help_text="User theme preference (light/dark)",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
