# Generated by Django 5.0.4 on 2025-11-12 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assistant", "0001_initial"),
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="approvebroadcast",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="Business user reviewing this broadcast",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="broadcast_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistant_bookings",
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistant_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactindex",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_indexes",
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversationthread",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="demandlead",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvebroadcast",
            name="demand_lead",
            field=models.ForeignKey(
                blank=True,
                help_text="The RFQ being broadcast",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broadcast_approvals",
                to="assistant.demandlead",
            ),
        ),
        migrations.AddField(
            model_name="agentbroadcast",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broadcasts",
                to="assistant.demandlead",
            ),
        ),
        migrations.AddIndex(
            model_name="failedtask",
            index=models.Index(
                fields=["-failed_at"], name="assistant_f_failed__427f95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="failedtask",
            index=models.Index(
                fields=["resolved"], name="assistant_f_resolve_c43770_idx"
            ),
        ),
        migrations.AddField(
            model_name="linksource",
            name="kb_article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="assistant.knowledgebase",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="Message recipient",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                help_text="Message sender (agent_service for broadcast_request) [Q4a]",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="preferenceextractionevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvebroadcast",
            name="request_fk",
            field=models.ForeignKey(
                blank=True,
                help_text="The generalized Request being broadcast",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broadcast_approvals",
                to="assistant.request",
            ),
        ),
        migrations.AddField(
            model_name="agentbroadcastv2",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broadcasts_v2",
                to="assistant.request",
            ),
        ),
        migrations.AddField(
            model_name="servicefeature",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="assistant.serviceprovider",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistant_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["listing", "-created_at"], name="assistant_b_listing_cb512e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "status"], name="assistant_b_user_id_019039_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationthread",
            index=models.Index(
                fields=["user", "is_active"], name="assistant_c_user_id_864caa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationthread",
            index=models.Index(
                fields=["thread_id"], name="assistant_c_thread__88da0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationthread",
            index=models.Index(
                fields=["user", "-created_at"], name="assistant_c_user_id_c9c227_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationthread",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user",),
                name="unique_active_thread_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["recipient", "is_unread"], name="assistant_m_recipie_3d82b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation_id", "-created_at"],
                name="assistant_m_convers_ff5580_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["type", "is_unread"], name="assistant_m_type_d54c54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["-created_at"], name="assistant_m_created_498048_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_msg_id__isnull", False)),
                fields=("conversation_id", "client_msg_id"),
                name="uniq_conversation_client_msg",
            ),
        ),
        migrations.AddIndex(
            model_name="preferenceextractionevent",
            index=models.Index(
                fields=["user", "-created_at"], name="pref_ext_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preferenceextractionevent",
            index=models.Index(
                fields=["thread_id", "-created_at"], name="pref_ext_thread_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preferenceextractionevent",
            index=models.Index(fields=["-created_at"], name="pref_ext_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="assistant_r_created_78f8ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["category", "location"], name="assistant_r_categor_0247ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["status"], name="assistant_r_status_87cead_idx"),
        ),
        migrations.AddIndex(
            model_name="approvebroadcast",
            index=models.Index(fields=["status"], name="assistant_a_status_254200_idx"),
        ),
        migrations.AddConstraint(
            model_name="approvebroadcast",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("demand_lead__isnull", False), ("request_fk__isnull", True)
                    ),
                    models.Q(
                        ("demand_lead__isnull", True), ("request_fk__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="approve_one_fk_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentbroadcastv2",
            constraint=models.UniqueConstraint(
                fields=("request", "seller_id"), name="uniq_broadcast_v2_request_seller"
            ),
        ),
        migrations.AddIndex(
            model_name="userpreference",
            index=models.Index(
                fields=["user", "category"], name="user_pref_user_cat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userpreference",
            index=models.Index(
                fields=["-confidence", "-last_used_at"],
                name="user_pref_conf_last_used_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userpreference",
            unique_together={("user", "category", "preference_type")},
        ),
    ]
