# Generated by Django 5.2.5 on 2025-08-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=36, unique=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='userrequest',
            old_name='number_of_peope',
            new_name='number_of_people',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='content_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='feature_name_tr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='description_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='demandlead',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandlead',
            name='source_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='demandlead',
            name='source_provider',
            field=models.CharField(choices=[('website', 'Website'), ('facebook', 'Facebook'), ('telegram', 'Telegram'), ('whatsapp', 'Whatsapp'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='demandlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('matched', 'Matched'), ('contacted', 'Outreach sent'), ('responded', 'User responded'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='demandlead',
            name='structured_lead',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='content_de',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='content_pl',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='content_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='keywords',
            field=models.CharField(help_text='Comma-separated keywords for AI search', max_length=500),
        ),
        migrations.AlterField(
            model_name='linksource',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ru', 'Russian'), ('pl', 'Polish'), ('de', 'German')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='raw_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='structured_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='booking_url',
            field=models.URLField(blank=True, help_text='Direct link for booking/reservations'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='category',
            field=models.CharField(choices=[('car_rental', 'Car Rental'), ('accommodation', 'Accommodation'), ('activities', 'Activities & Tours'), ('dining', 'Restaurants'), ('transportation', 'Transportation'), ('legal', 'Legal Services'), ('medical', 'Medical Services'), ('shopping', 'Shopping')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='price_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ru', 'Russian'), ('pl', 'Polish'), ('de', 'German')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='request_type',
            field=models.CharField(choices=[('car_rental', 'Car Rental'), ('accommodation', 'Accommodation'), ('activities', 'Things to Do'), ('dining', 'Restaurants & Dining'), ('transportation', 'Transportation'), ('legal', 'Legal Services'), ('medical', 'Medical Services'), ('shopping', 'Shopping'), ('human_assistance', 'Human Assistance'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('language', models.CharField(default='en', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
