# Generated by Django 5.0.4 on 2025-11-12 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="listing",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="userpreference",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="user",
        ),
        migrations.RemoveConstraint(
            model_name="approvebroadcast",
            name="approve_one_fk_set",
        ),
        migrations.AddConstraint(
            model_name="approvebroadcast",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("demand_lead__isnull", False), ("request_fk__isnull", True)
                    ),
                    models.Q(
                        ("demand_lead__isnull", True), ("request_fk__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="approve_exactly_one_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvebroadcast",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("demand_lead__isnull", True),
                    ("request_fk__isnull", True),
                    _negated=True,
                ),
                name="approve_not_both_null",
            ),
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
        migrations.DeleteModel(
            name="UserPreference",
        ),
    ]
