# Generated by Django 5.2.5 on 2025-08-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_channel',
            field=models.CharField(blank=True, help_text='e.., whatsapp, telegram', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_identifier',
            field=models.CharField(blank=True, help_text='e.g., phone number or chat id', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, help_text='Permament CDN/S3 URLs for photos'),
        ),
        migrations.AddField(
            model_name='listing',
            name='source_private_label',
            field=models.CharField(blank=True, help_text='internal tag for source; never surfaced', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(default='new', help_text='Internal lifecycle for proxy outreach', max_length=50),
        ),
    ]
