# Generated by Django 5.2.5 on 2025-10-22 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='demandlead',
            options={'permissions': [('can_broadcast_to_all_sellers', 'Can broadcast to all sellers')]},
        ),
        migrations.AddField(
            model_name='demandlead',
            name='extracted_criteria',
            field=models.JSONField(default=dict, help_text='Structured search/lead criteria extracted by NLU'),
        ),
        migrations.AddField(
            model_name='demandlead',
            name='handle_notes',
            field=models.TextField(blank=True, help_text='Internal notes / BI for this request'),
        ),
        migrations.AddField(
            model_name='demandlead',
            name='intent_type',
            field=models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='demandlead',
            name='sellers_contacted',
            field=models.JSONField(default=list, help_text='Audit log of sellers contacted for this request'),
        ),
        migrations.AddField(
            model_name='demandlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('broadcasted', 'Broadcasted'), ('responded', 'Responded'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='AgentBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_id', models.CharField(blank=True, help_text='Target seller/business identifier', max_length=64)),
                ('medium', models.CharField(help_text='email | sms | whatsapp', max_length=32)),
                ('status', models.CharField(default='pending', help_text='pending | sent | failed | responded | retrying', max_length=32)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('response_log', models.JSONField(default=dict, help_text='Optional payload of provider responses / metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='assistant.demandlead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
