# Generated by Django 5.2.5 on 2025-09-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_listing_contact_channel_listing_contact_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contact_channel',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('facebook', 'Facebook'), ('telegram', 'Telegram'), ('whatsapp', 'Whatsapp'), ('other', 'Other')], help_text='e.g., whatsapp, telegram', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_identifier',
            field=models.CharField(blank=True, db_index=True, help_text='e.g., E.164 phone number or chat id', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, help_text='Permanent CDN/S3 URLs for photos'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(blank=True, db_index=True, help_text="e.g., 'property_rent', 'car_sale'", max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='raw_text',
            field=models.TextField(blank=True, help_text='Original, unstructured post text'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source_id',
            field=models.CharField(db_index=True, help_text='Unique ID from the provider (e.g., post_id)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source_name',
            field=models.CharField(help_text="e.g., 'WhatsApp', 'Facebook', '101evler', etc.", max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source_private_label',
            field=models.CharField(blank=True, help_text='Internal tag for source; never surfaced to end users', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('verified_with_photos', 'Verified with Photos'), ('inactive', 'Inactive')], db_index=True, default='new', help_text='Internal lifecycle for proxy outreach', max_length=32),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_active', 'listing_type', 'last_seen_at'], name='assistant_l_is_acti_0556e9_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['location', 'last_seen_at'], name='assistant_l_locatio_eeee66_idx'),
        ),
    ]
