# Generated by Django 5.2.5 on 2025-09-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_alter_listing_contact_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('communication_style', models.CharField(default='casual', max_length=20)),
                ('detail_preference', models.CharField(default='moderate', max_length=20)),
                ('living_status', models.CharField(blank=True, max_length=50)),
                ('family_situation', models.CharField(blank=True, max_length=100)),
                ('work_situation', models.CharField(blank=True, max_length=100)),
                ('current_location', models.CharField(blank=True, max_length=100)),
                ('query_history', models.JSONField(default=list)),
                ('service_usage', models.JSONField(default=dict)),
                ('interests', models.JSONField(default=list)),
                ('goals', models.JSONField(default=list)),
                ('total_interactions', models.IntegerField(default=0)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('satisfaction_rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('current_topic', models.CharField(blank=True, max_length=200)),
                ('user_situation', models.JSONField(default=dict)),
                ('emotional_state', models.CharField(blank=True, max_length=50)),
                ('urgency_level', models.CharField(default='medium', max_length=20)),
                ('information_gaps', models.JSONField(default=list)),
                ('conversation_phase', models.CharField(default='initial', max_length=50)),
                ('active_goals', models.JSONField(default=list)),
                ('pending_actions', models.JSONField(default=list)),
                ('topic_history', models.JSONField(default=list)),
                ('decision_points', models.JSONField(default=list)),
                ('user_feedback', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistant.userprofile')),
            ],
        ),
    ]
