# Generated by Django 5.2.5 on 2025-10-23 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_featureflag_alter_demandlead_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(help_text='UUID identifying this conversation thread (LangGraph checkpoint key)', max_length=36, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active thread for this user (one active thread per user)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='assistant_c_user_id_864caa_idx'), models.Index(fields=['thread_id'], name='assistant_c_thread__88da0b_idx'), models.Index(fields=['user', '-created_at'], name='assistant_c_user_id_c9c227_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_thread_per_user')],
            },
        ),
    ]
