# Generated by Django 5.2.5 on 2025-10-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_add_conversation_thread_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ru', 'Russian'), ('pl', 'Polish')], default='en', help_text='User preferred language for chat', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='User theme preference (light/dark)', max_length=10),
        ),
    ]
