# Generated by Django 5.2.5 on 2025-09-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_userprofile_conversationcontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
