# Generated by Django 5.2.5 on 2025-09-03 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_message_message_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_contact', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_indexes', to='assistant.listing')),
            ],
            options={
                'unique_together': {('normalized_contact', 'listing')},
            },
        ),
    ]
