# Generated by Django 5.2.5 on 2025-10-23 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_add_user_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_seller_count', models.IntegerField(help_text='Number of sellers to be contacted')),
                ('seller_ids', models.JSONField(default=list, help_text='List of seller IDs targeted for this broadcast')),
                ('medium', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='whatsapp', help_text='Communication medium for broadcast', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired (24h timeout)')], default='pending', max_length=20)),
                ('approval_notes', models.TextField(blank=True, help_text='Business user notes on approval/rejection decision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('demand_lead', models.ForeignKey(help_text='The RFQ being broadcast', on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_approvals', to='assistant.demandlead')),
                ('reviewer', models.ForeignKey(blank=True, help_text='Business user reviewing this broadcast', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_approve_broadcasts', 'Can approve RFQ broadcasts'), ('can_reject_broadcasts', 'Can reject RFQ broadcasts')],
                'indexes': [models.Index(fields=['demand_lead', 'status'], name='assistant_a_demand__5392fe_idx'), models.Index(fields=['reviewer', 'status'], name='assistant_a_reviewe_9e8f0c_idx'), models.Index(fields=['-created_at'], name='assistant_a_created_fae121_idx')],
            },
        ),
    ]
