# Generated by Django 5.2.5 on 2025-10-23 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_add_approve_broadcast_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.AddField(
            model_name='message',
            name='broadcast_metadata',
            field=models.JSONField(blank=True, help_text='Structured criteria for broadcast_request (gatekept: location, budget, category, duration) [Q7, Q9]', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(db_index=True, default='legacy-conv', help_text='Links all messages in a thread (non-null for ALL types) [Q20]', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='demand_lead_id',
            field=models.CharField(blank=True, help_text='Foreign key to DemandLead (for Flow 2 messages)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_unread',
            field=models.BooleanField(db_index=True, default=True, help_text='Unread status (excludes system messages from badge count) [Q11]'),
        ),
        migrations.AddField(
            model_name='message',
            name='offer_metadata',
            field=models.JSONField(blank=True, help_text='Seller offer details for seller_response (price, availability, photos, details, links) [Q19c]', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when marked as read', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Message recipient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Message sender (agent_service for broadcast_request) [Q4a]', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('broadcast_request', 'Broadcast Request'), ('seller_response', 'Seller Response'), ('user', 'User Message'), ('assistant', 'Assistant Message'), ('system', 'System Message')], default='user', help_text='Message classification', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(help_text='Primary message text or summary'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_unread'], name='assistant_m_recipie_3d82b0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation_id', '-created_at'], name='assistant_m_convers_ff5580_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['type', 'is_unread'], name='assistant_m_type_d54c54_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='assistant_m_created_498048_idx'),
        ),
    ]
