# Generated by Django 5.2.5 on 2025-09-08 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_booking_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='assistant_b_listing_632d72_idx',
            old_name='assistant_bo_listing_6b8c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='assistant_b_user_id_019039_idx',
            old_name='assistant_bo_user_id_8c9d2e_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='assistant_b_preferr_43eb00_idx',
            old_name='assistant_bo_prefer_4a8b1c_idx',
        ),
        migrations.AddField(
            model_name='contactindex',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='assistant.conversation'),
        ),
    ]
