# Generated by Django 5.2.5 on 2025-10-23 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_alter_message_options_remove_message_conversation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('PROPERTY', 'Property'), ('VEHICLE', 'Vehicle'), ('GENERAL_PRODUCT', 'General Product'), ('SERVICE', 'Service'), ('KNOWLEDGE_QUERY', 'Knowledge Query'), ('OUT_OF_SCOPE', 'Out of Scope')], max_length=32)),
                ('subcategory', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_currency', models.CharField(blank=True, max_length=8)),
                ('attributes', models.JSONField(default=dict, help_text='Flexible attributes for domain-specific needs')),
                ('contact', models.CharField(help_text='User-provided contact (tokenized/redacted in serializers)', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending_approval', 'Pending Approval'), ('broadcasted', 'Broadcasted'), ('responded', 'Responded'), ('closed', 'Closed')], default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='assistant_r_created_78f8ab_idx'), models.Index(fields=['category', 'location'], name='assistant_r_categor_0247ee_idx'), models.Index(fields=['status'], name='assistant_r_status_87cead_idx')],
            },
        ),
    ]
