# Generated by Django 5.2.5 on 2025-09-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_add_conversation_to_contact_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pending_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
