# Generated by Django 5.2.5 on 2025-10-23 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBroadcastV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_id', models.CharField(blank=True, help_text='Target seller/business identifier', max_length=64)),
                ('medium', models.CharField(help_text='email | sms | whatsapp', max_length=32)),
                ('status', models.CharField(default='pending', help_text='pending | sent | failed | responded | retrying', max_length=32)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('response_log', models.JSONField(default=dict, help_text='Optional payload of provider responses / metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Broadcast V2',
                'verbose_name_plural': 'Agent Broadcasts V2',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='approvebroadcast',
            name='assistant_a_demand__5392fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvebroadcast',
            name='assistant_a_reviewe_9e8f0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvebroadcast',
            name='assistant_a_created_fae121_idx',
        ),
        migrations.AddField(
            model_name='approvebroadcast',
            name='request_fk',
            field=models.ForeignKey(blank=True, help_text='The generalized Request being broadcast', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_approvals', to='assistant.request'),
        ),
        migrations.AlterField(
            model_name='approvebroadcast',
            name='demand_lead',
            field=models.ForeignKey(blank=True, help_text='The RFQ being broadcast', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_approvals', to='assistant.demandlead'),
        ),
        migrations.AddIndex(
            model_name='approvebroadcast',
            index=models.Index(fields=['status'], name='assistant_a_status_254200_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvebroadcast',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('demand_lead__isnull', False), ('request_fk__isnull', True)), models.Q(('demand_lead__isnull', True), ('request_fk__isnull', False)), _connector='OR'), name='approve_one_fk_set'),
        ),
        migrations.AddField(
            model_name='agentbroadcastv2',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts_v2', to='assistant.request'),
        ),
    ]
