# Generated by Django 5.2.5 on 2025-10-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_agentbroadcastv2_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agentbroadcastv2',
            constraint=models.UniqueConstraint(fields=('request', 'seller_id'), name='uniq_broadcast_v2_request_seller'),
        ),
    ]
