# Generated by Django 5.2.5 on 2025-10-31 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0011_agentbroadcastv2_uniq_broadcast_v2_request_seller"),
        ("listings", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="demandlead",
            name="author_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="demandlead",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="demandlead",
            name="keywords_detected",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="demandlead",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demandlead",
            name="raw_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demandlead",
            name="source_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="demandlead",
            name="source_provider",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("twitter", "Twitter"),
                    ("linkedin", "LinkedIn"),
                    ("reddit", "Reddit"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="demandlead",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demandlead",
            name="structured_lead",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="message",
            name="client_msg_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Client-generated UUID for idempotency (prevents duplicate processing on network retry)",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["listing", "-created_at"], name="assistant_b_listing_cb512e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "status"], name="assistant_b_user_id_019039_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_msg_id__isnull", False)),
                fields=("conversation_id", "client_msg_id"),
                name="uniq_conversation_client_msg",
            ),
        ),
    ]
