# Generated by Django 5.2.5 on 2025-11-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0013_ensure_client_msg_id_on_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("args", models.JSONField()),
                ("exception", models.TextField()),
                ("failed_at", models.DateTimeField(auto_now_add=True)),
                ("retried_at", models.DateTimeField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-failed_at"],
                "indexes": [
                    models.Index(
                        fields=["-failed_at"], name="assistant_f_failed__427f95_idx"
                    ),
                    models.Index(
                        fields=["resolved"], name="assistant_f_resolve_c43770_idx"
                    ),
                ],
            },
        ),
    ]
