# Generated by Django 5.2.5 on 2025-11-03 09:55

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0014_gate_b_add_failed_task_dlq"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Ensure pgvector extension is installed
        VectorExtension(),
        migrations.CreateModel(
            name="PreferenceExtractionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("thread_id", models.CharField(db_index=True, max_length=255)),
                ("message_id", models.UUIDField(db_index=True)),
                ("utterance", models.TextField()),
                ("extracted_preferences", models.JSONField(default=list)),
                ("confidence_scores", models.JSONField(default=dict)),
                (
                    "extraction_method",
                    models.CharField(
                        choices=[
                            ("llm", "LLM (OpenAI)"),
                            ("rule", "Rule-based"),
                            ("hybrid", "Hybrid (LLM + Rules)"),
                            ("fallback", "Fallback Only"),
                        ],
                        max_length=50,
                    ),
                ),
                ("llm_reasoning", models.TextField(blank=True)),
                ("contradictions_detected", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processing_time_ms", models.IntegerField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "preference_extraction_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="preference__user_id_56ae5a_idx",
                    ),
                    models.Index(
                        fields=["thread_id", "-created_at"],
                        name="preference__thread__8cf160_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="preference__created_9434c0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("real_estate", "Real Estate"),
                            ("services", "Services"),
                            ("lifestyle", "Lifestyle"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("preference_type", models.CharField(db_index=True, max_length=50)),
                ("value", models.JSONField(help_text="Normalized structured value")),
                (
                    "raw_value",
                    models.TextField(
                        blank=True, help_text="Original utterance (PII-redacted)"
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("explicit", "Explicitly Stated"),
                            ("inferred", "Inferred from Context"),
                            ("behavior", "Learned from Behavior"),
                        ],
                        max_length=50,
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_decayed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("use_count", models.IntegerField(default=0)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("schema_version", models.IntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences",
                "ordering": ["-confidence", "-last_used_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "category"],
                        name="user_prefer_user_id_46d058_idx",
                    ),
                    models.Index(
                        fields=["-confidence", "-last_used_at"],
                        name="user_prefer_confide_80f7a2_idx",
                    ),
                ],
                "unique_together": {("user", "category", "preference_type")},
            },
        ),
    ]
