# Generated by Django 5.0.4 on 2025-11-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0017_add_preference_extraction_event"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userpreference",
            new_name="user_pref_user_cat_idx",
            old_name="user_prefer_user_id_46d058_idx",
        ),
        migrations.RenameIndex(
            model_name="userpreference",
            new_name="user_pref_conf_last_used_idx",
            old_name="user_prefer_confide_80f7a2_idx",
        ),
    ]
