# Generated by Django 5.0.4 on 2025-11-11 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assistant",
            "0018_rename_user_prefer_user_id_46d058_idx_user_pref_user_cat_idx_and_more",
        ),
        (
            "listings",
            "0006_rename_listings_bo_user_id_3a8f9c_idx_listings_bo_user_id_f12e91_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistant_bookings",
                to="listings.listing",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistant_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistant_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
