"""
Django settings for easy_islanders project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-^8j$q^-8r2s=1)&etjdrk%441b*r0f@urp(_9@&14409_1=luy')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Fail-fast if insecure key in production
if not DEBUG and (not SECRET_KEY or SECRET_KEY.startswith('django-insecure')):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "A valid SECRET_KEY is required in production. "
        "Set SECRET_KEY environment variable to a strong random value."
    )

# ALLOWED_HOSTS will be set later after CORS_ALLOWED_ORIGINS is defined
# to ensure alignment between CORS and Django host validation
ALLOWED_HOSTS = []  # Populated after CORS configuration


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'channels',  # WebSocket support

    # Local apps - users must come before assistant
    'users',
    'listings',
    'assistant',
    'router_service',
    'real_estate',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'assistant.monitoring.otel_instrumentation.RequestIDMiddleware',
    'assistant.monitoring.middleware.OpenTelemetryMiddleware',  # OpenTelemetry tracing
    'assistant.monitoring.middleware.MetricsMiddleware',  # Additional metrics
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'easy_islanders.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'easy_islanders.wsgi.application'
ASGI_APPLICATION = 'easy_islanders.asgi.application'

# Channels (WebSocket) Configuration
import os
from django.core.exceptions import ImproperlyConfigured

# Single canonical REDIS_URL read (used by Channels, Celery, Cache)
REDIS_URL = config('REDIS_URL', default='redis://127.0.0.1:6379/0')

# Fail-fast in production if Redis unavailable (no in-memory fallback)
if not DEBUG and not REDIS_URL:
    raise ImproperlyConfigured(
        "REDIS_URL is required in production for WebSocket support. "
        "In-memory channel layer is not suitable for multi-worker deployments."
    )

CHANNEL_LAYERS = {
    "default": (
        {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        } if REDIS_URL else
        {"BACKEND": "channels.layers.InMemoryChannelLayer"}  # dev-only convenience
    )
}

# Zep memory service configuration (disabled by default)
ZEP_ENABLED = config("ZEP_ENABLED", default=False, cast=bool)
ZEP_BASE_URL = config("ZEP_BASE_URL", default=None)
ZEP_API_KEY = config("ZEP_API_KEY", default=None)
ZEP_TIMEOUT_MS = config("ZEP_TIMEOUT_MS", default=1500, cast=int)
ZEP_API_VERSION = config("ZEP_API_VERSION", default=None)

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use dj_database_url for environment-based configuration
# This supports DATABASE_URL env var from Docker or local .env file
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',  # Use SQLite for local development
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Required for collectstatic

# Media (for uploaded/listing images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ISSUE-011 FIX: ChromaDB persistence directory (configurable, not hardcoded)
CHROMA_PERSIST_DIR = config('CHROMA_PERSIST_DIR', default=str(BASE_DIR / 'data' / 'chroma_db'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model (Phase 0 - Authentication)
AUTH_USER_MODEL = 'users.User'

# REST Framework & JWT Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'assistant.auth.cookies.CookieJWTAuthentication',  # PRIMARY: Cookie-based auth
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Fallback: Header auth
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Gate B: DRF throttling (proper 429 responses)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '10/min',  # Matches PR C spec
    },
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(config('ACCESS_TOKEN_MINUTES', default='60'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ALGORITHM': 'HS256',
    'LEEWAY': 60,  # Clock skew tolerance in seconds for distributed systems
}

# ===== JWT Cookie Configuration (PR D: Auth Hardening) =====
JWT_COOKIE_SECURE = not DEBUG  # Only send over HTTPS in production
JWT_COOKIE_SAMESITE = 'Lax'    # CSRF protection while allowing normal navigation
FEATURE_FLAG_ALLOW_QUERY_TOKEN = DEBUG  # Query param auth only in dev (WebSocket)
FEATURE_FLAG_ALLOW_HEADER_AUTH = True   # Allow Authorization header for non-browser clients

# ===== Session & CSRF Security =====
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True  # Prevent JS access
CSRF_COOKIE_SAMESITE = 'Lax'

# ✅ CORS Configuration for credentials support
# When using withCredentials: true on frontend, cannot use wildcard '*'
# Must specify exact allowed origins
CORS_ALLOW_ALL_ORIGINS = False

# Base dev-friendly CORS origins
_default_cors = {
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
}

# Optionally extend via env (comma-separated)
_cors_env = {o.strip() for o in config('CORS_ALLOWED_ORIGINS', default='').split(',') if o.strip()}
CORS_ALLOWED_ORIGINS = sorted(_default_cors.union(_cors_env))
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    'authorization',
    'x-correlation-id',
]

# CSRF trusted origins (needed if using session auth or admin from a different host)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

# ALLOWED_HOSTS Configuration - Aligned with CORS for security
from urllib.parse import urlparse

if DEBUG:
    # Development: allow all for convenience
    # Include 'web' explicitly for Docker Compose internal calls
    ALLOWED_HOSTS = ['*', 'web', 'localhost', '127.0.0.1']
else:
    # Production: only explicit hosts derived from CORS origins + health check hosts
    _cors_hosts = [urlparse(origin).netloc for origin in CORS_ALLOWED_ORIGINS if origin]
    ALLOWED_HOSTS = [h for h in _cors_hosts if h] + [
        'host.docker.internal',  # Docker/K8s health checks
        '127.0.0.1',
        'localhost',
        'web',  # Docker Compose service name
        '172.19.0.0/16',  # Fly.io internal network
    ]

# --- DECOUPLE AND AI CONFIGURATION ---
# This part is crucial for reading the .env file

# AI ASSISTANT CONFIGURATION
# The config() function reads the value from your .env file
# ISSUE-005 FIX: Validate critical env vars in production
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')

# Validate required env vars for production (not in DEBUG mode)
if not DEBUG and not OPENAI_API_KEY:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "OPENAI_API_KEY is required in production. Set it in your environment variables."
    )

# Enhanced Agent Context - Feature Flag (default: disabled for safety)
ENABLE_AGENT_CONTEXT = config('ENABLE_AGENT_CONTEXT', default='false').lower() == 'true'

# Cache configuration with optional Redis
# Note: REDIS_URL is already defined in Channels section above
USE_REDIS_CACHE = config('USE_REDIS_CACHE', default=False, cast=bool)

if USE_REDIS_CACHE:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                # Swallow redis errors as cache misses instead of crashing requests
                "IGNORE_EXCEPTIONS": True,
            },
            "TIMEOUT": 300,
        }
    }
else:
    # Development-friendly in-memory cache
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "easy_islanders_local_cache",
            "TIMEOUT": 300,
        }
    }

# Celery Configuration
# Use the already-resolved REDIS_URL as the default to avoid decouple looking up a literal URL as an env var
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=REDIS_URL)
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=REDIS_URL)
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE
# Allow long-running chat tasks (LLM calls can take 30-120s legitimately)
CELERY_TASK_TIME_LIMIT = 180  # Hard limit: kill task after 180s
CELERY_TASK_SOFT_TIME_LIMIT = 150  # Soft limit: warn after 150s
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# --- Celery queues & routing (Gate B: Operational Hardening) ---
CELERY_TASK_IGNORE_RESULT = True  # we don't need results for enqueue-only
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_ROUTES = {
    "assistant.tasks.process_chat_message": {"queue": "chat"},
    # background jobs -> lower priority queue
    "assistant.tasks.process_incoming_media_task": {"queue": "background"},
    "assistant.tasks.trigger_get_and_prepare_card_task": {"queue": "background"},
    "assistant.tasks.send_whatsapp_message_task": {"queue": "notifications"},
    "assistant.tasks.broadcast_request_for_request": {"queue": "background"},
    "assistant.tasks.update_calibration_params": {"queue": "background"},
    "assistant.tasks.dispatch_broadcast": {"queue": "background"},
}
# Fair scheduling; avoid big tasks starving small ones
CELERYD_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_ENABLE_REMOTE_CONTROL = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Observability: Enable task event tracking for monitoring
CELERY_TASK_TRACK_STARTED = True  # Emit task-started event (not just queued)
CELERY_TASK_SEND_SENT_EVENT = True  # Emit task-sent event
CELERY_WORKER_SEND_TASK_EVENTS = True  # Worker lifecycle events
CELERY_SEND_EVENTS = True  # Enable event dispatcher

# Structured logging for task states
CELERY_REDIRECT_STDOUTS_LEVEL = "INFO"  # Capture task stdout/stderr
OPENAI_MODEL = config('OPENAI_MODEL', default='gpt-4-turbo-preview')

# Proactive Agent Configuration
PROACTIVE_AGENT_ENABLED = config('PROACTIVE_AGENT_ENABLED', default=False, cast=bool)
ENABLE_PROACTIVE_PHOTOS = config('ENABLE_PROACTIVE_PHOTOS', default=False, cast=bool)
ENABLE_PROACTIVE_REMINDERS = config('ENABLE_PROACTIVE_REMINDERS', default=False, cast=bool)
ENABLE_PROACTIVE_QUESTIONS = config('ENABLE_PROACTIVE_QUESTIONS', default=False, cast=bool)
ENABLE_PROACTIVE_PREDICTIONS = config('ENABLE_PROACTIVE_PREDICTIONS', default=False, cast=bool)

# Auto-Response Configuration
ENABLE_AUTO_RESPONSE = config('ENABLE_AUTO_RESPONSE', default=False, cast=bool)

# LangGraph Agent Configuration (Phase A: Safe Rollout)
ENABLE_LANGGRAPH_AGENT = config('ENABLE_LANGGRAPH_AGENT', default=False, cast=bool)

# Central Supervisor Agent (Hierarchical Router)
ENABLE_SUPERVISOR_AGENT = config('ENABLE_SUPERVISOR_AGENT', default=False, cast=bool)
SUPERVISOR_ROUTER_MODEL = config('SUPERVISOR_ROUTER_MODEL', default='gpt-4o-mini')

# LangGraph Checkpointing Configuration (Phase A: In-memory with MemorySaver)
# Phase B will upgrade to PostgreSQL when needed (> 50 concurrent users)
LANGGRAPH_CHECKPOINT_CONNECTION_STRING = config(
    'LANGGRAPH_CHECKPOINT_CONNECTION_STRING',
    default='sqlite:///langgraph_checkpoints.db'
)

MAX_PROACTIVE_MESSAGES_PER_DAY = config('MAX_PROACTIVE_MESSAGES_PER_DAY', default=3, cast=int)
PROACTIVE_RATE_LIMIT_WINDOW = config('PROACTIVE_RATE_LIMIT_WINDOW', default=3600, cast=int)  # 1 hour

# End Celery config

# Enterprise Multi-Domain Agent Configuration (Phase B: Production Ready)
ENABLE_ENTERPRISE_AGENT = config('ENABLE_ENTERPRISE_AGENT', default=True, cast=bool)

# Registry Service Configuration
REGISTRY_BASE_URL = config('REGISTRY_BASE_URL', default='http://localhost:8081')
REGISTRY_API_KEY = config('REGISTRY_API_KEY', default='dev-key')

# OpenTelemetry Configuration
OTEL_EXPORTER_OTLP_ENDPOINT = config('OTEL_EXPORTER_OTLP_ENDPOINT', default='http://localhost:4317')
OTEL_SERVICE_NAME = config('OTEL_SERVICE_NAME', default='easy-islanders')
OTEL_SERVICE_VERSION = config('OTEL_SERVICE_VERSION', default='1.0.0')
ENVIRONMENT = config('ENVIRONMENT', default='staging')

# Sampling Configuration
OTEL_TRACES_SAMPLER = config('OTEL_TRACES_SAMPLER', default='traceidratio')
if ENVIRONMENT == 'production':
    OTEL_TRACES_SAMPLER_ARG = config('OTEL_TRACES_SAMPLER_ARG', default='0.2')  # 20% sampling for production
else:
    OTEL_TRACES_SAMPLER_ARG = config('OTEL_TRACES_SAMPLER_ARG', default='1.0')  # 100% sampling for staging

# Error sampling (always 100%)
OTEL_ERROR_SAMPLER_ARG = config('OTEL_ERROR_SAMPLER_ARG', default='1.0')

# Enable OpenTelemetry metrics
ENABLE_OTEL_METRICS = config('ENABLE_OTEL_METRICS', default=True, cast=bool)

# LLM Metrics Configuration
LLM_METRICS_SAMPLE_RATE = float(OTEL_TRACES_SAMPLER_ARG)
LLM_METRICS_ERROR_SAMPLE_RATE = 1.0  # Always sample errors

# DRF Spectacular Configuration
SPECTACULAR_SETTINGS = {
    "TITLE": "Easy Islanders API",
    "DESCRIPTION": "Public/Private endpoints for chat, listings, bookings, messages, agents.",
    "VERSION": "1.0.0",
    # If you use JWT/Bearer across most endpoints, set global security:
    "SECURITY": [{"bearerAuth": []}],
    "COMPONENT_SPLIT_REQUEST": True,  # better request/response separation in UI
    "SERVERS": [{"url": "/api/", "description": "Default API root"}],
    # Optional: show extensions like x-codeSamples if you add them
    # "POSTPROCESSING_HOOKS": [],
}

# Router Configuration (Sprint 5)
ROUTER_FUSION_WEIGHTS = {
    'embed_score': 0.15,
    'clf_prob': 0.7,
    'rule_vote': 0.15,
}
ROUTER_TAU_DEFAULT = 0.72
ROUTER_TAU_MIN = 0.60
ROUTER_DELTA_TOP2 = 0.08
ROUTER_CALIBRATION_VERSION = "v1.5"
ROUTER_ENABLE_AB = False

# Production Safety Toggles
# ALLOW_ANY_SCHEME_IN_URLS: Allow non-HTTPS URLs in development
# Set to "false" in production environments
ALLOW_ANY_SCHEME_IN_URLS = os.getenv("ALLOW_ANY_SCHEME_IN_URLS", "false").lower() == "true"

# Structured JSON logging for assistant.* loggers
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'correlation': {
            '()': 'assistant.utils.correlation.CorrelationIdFilter',
        },
    },
    'formatters': {
        'json': {
            '()': 'assistant.monitoring.logging_utils.JSONFormatter',
        },
        'simple': {
            'format': '[%(levelname)s] [cid=%(correlation_id)s] %(name)s: %(message)s'
        },
    },
    'handlers': {
        'console_json': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
            'filters': ['correlation'],
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['correlation'],
        },
    },
    'loggers': {
        'assistant': {
            'handlers': ['console_json'],
            'level': 'INFO',
            'propagate': True,
        },
        'assistant.monitoring': {
            'handlers': ['console_json'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
