# Generated by Django 5.0.4 on 2025-11-12 12:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        ("users", "0002_userpreference_delete_userpreferences_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated booking reference (e.g., BK-2024-0001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Booking start date/time"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Booking end date/time (nullable for appointments)",
                        null=True,
                    ),
                ),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "service_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "taxes",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=10)),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_phone", models.CharField(max_length=50)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "special_requests",
                    models.TextField(blank=True, help_text="Customer special requests"),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal staff notes (not visible to customer)",
                    ),
                ),
                (
                    "guests_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total number of guests",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "booking_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific flexible data (amenities, preferences, etc.)",
                    ),
                ),
                (
                    "cancellation_policy",
                    models.CharField(
                        choices=[
                            ("flexible", "Flexible: Full refund up to 24h before"),
                            ("moderate", "Moderate: 50% refund up to 5 days before"),
                            ("strict", "Strict: 50% refund up to 30 days before"),
                            ("non_refundable", "Non-refundable"),
                        ],
                        default="flexible",
                        max_length=20,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partial", "Partially Paid"),
                            ("paid", "Paid in Full"),
                            ("refunded", "Refunded"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        help_text="Listing being booked (nullable for appointments)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Apartment Rental')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly identifier", unique=True),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Lucide icon name", max_length=100
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6CC24A",
                        help_text="Brand color for this type",
                        max_length=50,
                    ),
                ),
                (
                    "requires_dates",
                    models.BooleanField(
                        default=True, help_text="Requires start/end dates"
                    ),
                ),
                (
                    "requires_time_slot",
                    models.BooleanField(
                        default=False, help_text="Requires specific time slots"
                    ),
                ),
                (
                    "requires_guests",
                    models.BooleanField(default=True, help_text="Requires guest count"),
                ),
                (
                    "requires_vehicle_info",
                    models.BooleanField(
                        default=False, help_text="Requires vehicle/driver info"
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON schema defining type-specific form fields",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Booking Type",
                "verbose_name_plural": "Booking Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ApartmentRentalBooking",
            fields=[
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="apartment_rental",
                        serialize=False,
                        to="bookings.booking",
                    ),
                ),
                (
                    "number_of_guests",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "number_of_adults",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("number_of_children", models.PositiveIntegerField(default=0)),
                ("number_of_infants", models.PositiveIntegerField(default=0)),
                ("pets_allowed", models.BooleanField(default=False)),
                ("bringing_pets", models.BooleanField(default=False)),
                ("pet_details", models.TextField(blank=True)),
                ("smoking_allowed", models.BooleanField(default=False)),
                ("check_in_instructions", models.TextField(blank=True)),
                ("wifi_password", models.CharField(blank=True, max_length=100)),
                ("parking_info", models.TextField(blank=True)),
                (
                    "amenities_requested",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of requested amenities",
                    ),
                ),
                ("cleaning_service", models.BooleanField(default=False)),
                ("cleaning_frequency", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Apartment Rental Booking",
                "verbose_name_plural": "Apartment Rental Bookings",
            },
        ),
        migrations.CreateModel(
            name="ApartmentViewingBooking",
            fields=[
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="viewing",
                        serialize=False,
                        to="bookings.booking",
                    ),
                ),
                ("viewing_date", models.DateField()),
                ("viewing_time", models.TimeField()),
                (
                    "viewing_duration_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Duration in minutes"
                    ),
                ),
                ("interested_in_buying", models.BooleanField(default=False)),
                ("interested_in_renting", models.BooleanField(default=False)),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("agent_name", models.CharField(blank=True, max_length=255)),
                ("agent_contact", models.CharField(blank=True, max_length=50)),
                ("agent_company", models.CharField(blank=True, max_length=255)),
                ("viewing_completed", models.BooleanField(default=False)),
                ("feedback_notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Viewing Booking",
                "verbose_name_plural": "Viewing Bookings",
            },
        ),
        migrations.CreateModel(
            name="BookingHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("payment_received", "Payment Received"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=50,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="bookings.booking",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking History",
                "verbose_name_plural": "Booking Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="Overall rating (1-5 stars)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review_text", models.TextField()),
                (
                    "cleanliness_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "communication_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "value_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "location_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "response",
                    models.TextField(blank=True, help_text="Seller response to review"),
                ),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verified booking review"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="bookings.booking",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Review",
                "verbose_name_plural": "Booking Reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="bookings.bookingtype",
            ),
        ),
        migrations.CreateModel(
            name="AppointmentBooking",
            fields=[
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="appointment",
                        serialize=False,
                        to="bookings.booking",
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("hair", "Hair Salon"),
                            ("beauty", "Beauty/Spa"),
                            ("medical", "Medical"),
                            ("dental", "Dental"),
                            ("consultation", "Consultation"),
                            ("fitness", "Fitness/Training"),
                            ("legal", "Legal"),
                            ("financial", "Financial"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("recurring", models.BooleanField(default=False)),
                (
                    "recurrence_pattern",
                    models.CharField(
                        blank=True,
                        help_text="daily, weekly, monthly, etc.",
                        max_length=50,
                    ),
                ),
                ("recurrence_end_date", models.DateField(blank=True, null=True)),
                ("appointment_notes", models.TextField(blank=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("no_show", models.BooleanField(default=False)),
                (
                    "rescheduled_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rescheduled_appointments",
                        to="bookings.appointmentbooking",
                    ),
                ),
                (
                    "service_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="users.businessprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Booking",
                "verbose_name_plural": "Appointment Bookings",
            },
        ),
        migrations.CreateModel(
            name="CarRentalBooking",
            fields=[
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="car_rental",
                        serialize=False,
                        to="bookings.booking",
                    ),
                ),
                ("pickup_location", models.CharField(max_length=500)),
                ("dropoff_location", models.CharField(max_length=500)),
                ("pickup_datetime", models.DateTimeField()),
                ("dropoff_datetime", models.DateTimeField()),
                ("driver_license_number", models.CharField(max_length=100)),
                (
                    "driver_age",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("driver_country", models.CharField(blank=True, max_length=100)),
                (
                    "insurance_selected",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Coverage"),
                            ("standard", "Standard Coverage"),
                            ("premium", "Premium Full Coverage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("additional_drivers", models.PositiveIntegerField(default=0)),
                ("additional_driver_names", models.TextField(blank=True)),
                (
                    "fuel_policy",
                    models.CharField(
                        choices=[
                            ("full_to_full", "Full to Full"),
                            ("same_to_same", "Same to Same"),
                            ("prepaid", "Prepaid Fuel"),
                        ],
                        default="full_to_full",
                        max_length=20,
                    ),
                ),
                (
                    "mileage_limit",
                    models.PositiveIntegerField(
                        default=200, help_text="Km per day limit (0 for unlimited)"
                    ),
                ),
                ("gps_requested", models.BooleanField(default=False)),
                ("child_seat_requested", models.BooleanField(default=False)),
                ("number_of_child_seats", models.PositiveIntegerField(default=0)),
                ("fuel_level_pickup", models.CharField(blank=True, max_length=20)),
                ("fuel_level_return", models.CharField(blank=True, max_length=20)),
                (
                    "mileage_at_pickup",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "mileage_at_return",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_rental_bookings",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Rental Booking",
                "verbose_name_plural": "Car Rental Bookings",
            },
        ),
        migrations.CreateModel(
            name="HotelBooking",
            fields=[
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="hotel",
                        serialize=False,
                        to="bookings.booking",
                    ),
                ),
                ("room_type", models.CharField(max_length=100)),
                (
                    "number_of_rooms",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "number_of_guests",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "meal_plan",
                    models.CharField(
                        choices=[
                            ("none", "No Meals"),
                            ("breakfast", "Breakfast Only"),
                            ("half_board", "Half Board (Breakfast + Dinner)"),
                            ("full_board", "Full Board (All Meals)"),
                            ("all_inclusive", "All Inclusive"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "smoking_preference",
                    models.CharField(
                        choices=[
                            ("non_smoking", "Non-Smoking"),
                            ("smoking", "Smoking"),
                        ],
                        default="non_smoking",
                        max_length=20,
                    ),
                ),
                ("floor_preference", models.CharField(blank=True, max_length=50)),
                ("bed_type", models.CharField(blank=True, max_length=50)),
                ("early_checkin_requested", models.BooleanField(default=False)),
                ("late_checkout_requested", models.BooleanField(default=False)),
                ("airport_transfer_requested", models.BooleanField(default=False)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_bookings",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel Booking",
                "verbose_name_plural": "Hotel Bookings",
            },
        ),
        migrations.CreateModel(
            name="ServiceBooking",
            fields=[
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="service",
                        serialize=False,
                        to="bookings.booking",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("cleaning", "Cleaning"),
                            ("repair", "Repair"),
                            ("maintenance", "Maintenance"),
                            ("plumbing", "Plumbing"),
                            ("electrical", "Electrical"),
                            ("painting", "Painting"),
                            ("gardening", "Gardening"),
                            ("moving", "Moving"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("service_location_address", models.CharField(max_length=500)),
                ("service_location_access_instructions", models.TextField(blank=True)),
                (
                    "equipment_needed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of equipment provider should bring",
                    ),
                ),
                (
                    "estimated_duration_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("service_started_at", models.DateTimeField(blank=True, null=True)),
                ("service_completed_at", models.DateTimeField(blank=True, null=True)),
                ("service_completed", models.BooleanField(default=False)),
                ("completion_notes", models.TextField(blank=True)),
                (
                    "service_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="listings.Category",
                    ),
                ),
                (
                    "service_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_bookings",
                        to="users.businessprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Booking",
                "verbose_name_plural": "Service Bookings",
            },
        ),
        migrations.CreateModel(
            name="BookingAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("max_bookings", models.PositiveIntegerField(default=1)),
                ("current_bookings", models.PositiveIntegerField(default=0)),
                ("blocked_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="listings.listing",
                    ),
                ),
                (
                    "service_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="users.businessprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Availability",
                "verbose_name_plural": "Booking Availabilities",
                "indexes": [
                    models.Index(
                        fields=["listing", "date"],
                        name="bookings_bo_listing_f760fb_idx",
                    ),
                    models.Index(
                        fields=["service_provider", "date"],
                        name="bookings_bo_service_af5ad2_idx",
                    ),
                ],
                "unique_together": {
                    ("listing", "service_provider", "date", "start_time")
                },
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "-created_at"], name="bookings_bo_user_id_6151bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["listing", "start_date", "end_date"],
                name="bookings_bo_listing_437bd0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_type", "status"], name="bookings_bo_booking_d9ba59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["reference_number"], name="bookings_bo_referen_77bb3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "status"], name="bookings_bo_user_id_69a5d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["payment_status"], name="bookings_bo_payment_27706e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "-created_at"], name="bookings_bo_status_eb4fb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["start_date", "status"], name="bookings_bo_start_d_e64553_idx"
            ),
        ),
    ]
